### ISSUE TITLE
Use OpenMP in Silicon::accumulate function.

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#1008]
For future LSST DESC ImSim runs, we would like to potentially use OpenMP to parallelize the Silicon class's [`accumulate`](https://github.com/GalSim-developers/GalSim/blob/releases/2.1/src/Silicon.cpp#L462) method, particularly when accumulating a large number of photons.

Specifically, we should parallelize the loop over photons, but we need to be careful to avoid race conditions (e.g. when calling `updatePixelDistortions` and when adding the flux to the `_delta` array and `addedFlux`).

The call to [`updatePixelDistortions`](https://github.com/GalSim-developers/GalSim/blob/releases/2.1/src/Silicon.cpp#L157) probably need to be atomic in this context, but it too might be able to parallelize its calculation over pixels.

When working on this, tests/test_silicon.py will be a good test that you haven't broken anything.  And devel/time_phot.py will be a decent test of the timing.  (We might want to write some additional timing tests that are more targeted to what we will want, but this isn't too bad.)

**Comment by jamesp-epcc** [comment]
I have started adding OpenMP to this method. I have forked the repo and am checking in my progress here: https://github.com/jamesp-epcc/GalSim/blob/releases/2.1/src/Silicon.cpp . So far I have parallelised the main loop over photons. It's not giving quite the same results as the old serial version, but this may just be because of random number sequences being different, and `updatePixelDistortions` being called at subtly different times (which is going to be difficult to avoid completely). It is speeding things up a bit but not as much as I'd hoped. This may improve if I can get `updatePixelDistortions` to run in parallel as well.
I have also started looking at parallelising `updatePixelDistortions` itself but my first attempt didn't work properly so I will have to try something more complex.

**Comment by jamesp-epcc** [comment]
I have parallelised `updatePixelDistortions` and it is now working. It required some operations in `Polygon::distort` to be made atomic. I will now return to working on the `accumulate` method itself.

**Comment by jamesp-epcc** [comment]
I have tested the parallelised code on Cori KNL and Haswell. The graphs below show the scaling of the code when running the "resume and no resume" test from `test_sensor.py`. This is with only `updatePixelDistortions` parallelised. The scaling is reasonably good even with just this function parallelised. The "resume" case shows much less improvement, probably because it is starting from a much faster baseline. The "no resume" case scales well up to about 8 threads on both Haswell and KNL, though there is less benefit beyond this level.

![haswell_openmp](https://user-images.githubusercontent.com/14821192/55485870-33897000-5623-11e9-8d0e-05b966b0b6b5.png)

![knl_openmp](https://user-images.githubusercontent.com/14821192/55485871-34220680-5623-11e9-8c54-03a3aa7e400e.png)

I also tested with the photon loop in `accumulate` parallelised, even though I am not yet sure my parallelised version is correct, to get an idea of how much difference this would make. It is actually slower on Haswell than the original serial version, and on Cori it is slower when running with less than 8 threads. This is probably because of the serialisation necessary to ensure that only one thread calls `updatePixelDistortions`. I will try using a critical section for this instead of my initial approach of moving this completely outside the parallel section.

**Comment by jamesp-epcc** [comment]
I have tried an alternative method for parallelising the `accumulate` photon loop but it is just as slow as my first attempt. Unfortunately it's difficult to get high performance due to the synchronisation required between the threads (because some operations in the loop must be serialised). I will have another think and see if I can come up with a better solution.

**Comment by jamesp-epcc** [comment]
I have tried another method for parallelising the `accumulate` photon loop. This time each thread loops independently until it is time to compute the distortions, rather than the loop being outside the parallel section, or inside but with multiple barriers to control synchronisation, as in my previous attempts. This speeds up the "with resume" case on KNL but makes very little difference to the "without resume" case, or to either case on Haswell (see graphs below). The results do not match the output from the original serial code; I believe this is due to `updatePixelDistortions` being called at slightly different points in the photon loop, as well as different sequences from the random number generators. I am not sure whether the differences will be acceptable or not, however it is useful to get an idea of how much benefit is likely to be available through OpenMP.

![haswell_openmp2](https://user-images.githubusercontent.com/14821192/55623204-30fd5680-579a-11e9-90b1-352e2b60946b.png)

![knl_openmp2](https://user-images.githubusercontent.com/14821192/55623205-3195ed00-579a-11e9-806d-d833c317c56b.png)

**Comment by cwwalter** [comment]
It's also sort of interesting that, if you look at one thread cas, the speed difference between KNL and Haswell is so large.  It's seems to comparable to what we are seeing with all of imSim (~x8).  But this is just the C++ code in GalSim so Python has nothing to do with it.  Am I interpreting the graphs/test correctly?

**Comment by jamesp-epcc** [comment]
That's correct, it's about an 8x difference. I remember seeing something similar with a simple C++ test code that I tried a year or two ago so that sort of difference can happen.

**Comment by jamesp-epcc** [comment]
It's possible. I'll have a look at what options are being used.

**Comment by jamesp-epcc** [comment]
I tested some different compiler options to see if they would speed up GalSim on KNL. I was hopeful about the `-mfma` option as it (unexpectedly) sped up my trivial test program from 8x slower than Haswell to only 5x slower. But unfortunately it had no effect on GalSim and neither did any of the other options I tried (`-O3`, `-mavx`, `-finline-functions`).

**Comment by jamesp-epcc** [comment]
I've been working on making the code reproducible as we discussed, so that I can check the results from multithread runs against the single threaded version. I've also parallelised the main accumulate loop using a new strategy. This appears to scale quite a lot better than before and is passing the tests. I still haven't tried a separate delta image per thread yet.

I'm out of time for today now but I will check in the new code and post detailed performance information soon.

I've also worked on profiling but I haven't succeeded in getting any of the standard profiling tools to work on the code, probably because it's a shared library called from Python. However I have got some basic information on how long the code spends in various regions using some code I wrote in the past and will explore this further to try and find out why the scaling is tailing off.

**Comment by rmjarvis** [comment]
It's pretty tricky to profile C++ code called from Python.  My usual technique is to use Instruments on my (Mac) laptop.  I've tried to get various Linux profilers working, but without success, so I'm afraid I don't have any good suggestions there.

**Comment by jamesp-epcc** [comment]
I have finished making the code reproducible and parallelising it again. It scales a bit better than before, though the improvement still flattens off at around 16-32 threads. Results for KNL and Haswell:
![haswell_reproducible](https://user-images.githubusercontent.com/14821192/56354424-92c2b500-61cb-11e9-82bf-467626ca4fae.png)
![knl_reproducible](https://user-images.githubusercontent.com/14821192/56354425-935b4b80-61cb-11e9-91e8-18e765342274.png)

I tested with a separate delta image per thread, however this made very little difference and low thread counts and was actually slightly slower at higher thread counts, due to the overhead of summing all the delta images into one. Results for KNL and Haswell:
![haswell_delta](https://user-images.githubusercontent.com/14821192/56354551-f77e0f80-61cb-11e9-9ce3-42f743263161.png)
![knl_delta](https://user-images.githubusercontent.com/14821192/56354552-f77e0f80-61cb-11e9-9a49-85eb7fd6f88e.png)

In order to test my hypothesis that the scaling was being adversely affected by the serialised calls to `updatePixelDistortions`, I tested the code with this function completely disabled. It is faster, as expected, but the scaling still flattens off at about the same thread count as before, suggesting that this is not the limiting factor for the scaling. KNL results:
![knl_no_distortion](https://user-images.githubusercontent.com/14821192/56354655-44fa7c80-61cc-11e9-8152-db5191d748e2.png)

I have profiled the accumulate loop in a bit more detail (by instrumenting it with my own profiling code as I have still had no luck with the standard tools). There does not appear to be a single "hot spot" taking the vast majority of the time, though the most time consuming operations appear to be the calls to `calculateConversionDepth` and `insidePixel`. The actual addition of the flux to the delta image is very fast, despite the atomic operation.

**Comment by rmjarvis** [comment]
I think for the timing tests, you should move away from using test_sensor.  It probably doesn't have enough photons to be particularly interesting for real timing tests, which is likely why things stop improving after only ~20 cores.  

I suggested in the header post of this issue using devel/time_phot.py for timing.  That is a more significant calculation that is probably more relevant for this effort.

**Comment by jamesp-epcc** [comment]
Thanks, I will run some tests with `time_phot.py` now that I have a working parallel version of the loop.

**Comment by cwwalter** [comment]
Do you understand what the main difference in the parallelization strategy that made it flatten our later is?

**Comment by jamestperry** [comment]
The newer parallelisation strategy counts up how many photons should be fired before the next call to `updatePixelDistortions` before the main loop. This firstly makes it reproducible, but also means that the parallel code no longer has to count up the added flux and exit the loop when it reaches a certain value. This removes the need to synchronise between the threads in the loop (except for actually adding the flux to the image which is a pretty lightweight atomic addition).

**Comment by jamesp-epcc** [comment]
The newer parallelisation strategy counts up how many photons should be fired before the next call to `updatePixelDistortions` before the main loop. This firstly makes it reproducible, but also means that the parallel code no longer has to count up the added flux and exit the loop when it reaches a certain value. This removes the need to synchronise between the threads in the loop (except for actually adding the flux to the image which is a pretty lightweight atomic addition).

**Comment by jamesp-epcc** [comment]
I tried `time_phot.py` but it didn't seem to be exercising the photon loop - it was printing out `nphotons=0` and it didn't get any faster when I increased the thread count. However I have run a larger test using `test_sensor.py`, using 400 photons per pixel instead of the original 40. This does show slightly better scaling than the previous cases. Although it's hard to see properly from the graphs, it continues to get faster up to 128 threads on KNL and 64 on Haswell.
![haswell_400ppp](https://user-images.githubusercontent.com/14821192/56500860-5f9e5f80-6504-11e9-8f26-e95353f3c17c.png)
![knl_400ppp](https://user-images.githubusercontent.com/14821192/56500861-5f9e5f80-6504-11e9-91f6-82eb746ac973.png)

**Comment by jamesp-epcc** [comment]
I've written a new test case for this which is hopefully on a more suitable scale. It's in `devel/test_silicon_accumulate.py`. It uses a 1000x1000 pixel image and 10,000,000 photons (randomly placed currently though this could be changed). It only uses the basic settings of the silicon object which also might need to be changed to make it a more realistic test.
Scaling is better than with the `test_sensor.py` tests. On KNL it continues to scale reasonably well up to 128 threads, ultimately running 60 times faster than the single threaded version. On Haswell it scales up to 32 threads, reaching around 14 times the speed of the serial version. Graphs are below.
![haswell_test_silicon_accumulate](https://user-images.githubusercontent.com/14821192/57386841-25dc8280-71ad-11e9-879c-d2fdc49d77ef.png)
![knl_test_silicon_accumulate](https://user-images.githubusercontent.com/14821192/57386842-25dc8280-71ad-11e9-92ae-e43638cf6e30.png)

**Comment by cwwalter** [comment]
Hi James,

Great thanks.  It looks like this would be a good starting point for us to use when the imSim refactor is ready.  We talked about this in the meeting this morning.  Could you start the process of a PR here in GalSim on this work?

**Comment by jamesp-epcc** [comment]
Hi Chris. Sure, I will do that this week. Sorry for the late reply, I am just back from holiday today.

**Comment by rmjarvis** [comment]
Done. #1028
