### ISSUE TITLE
Add WFIRST R062 filter information to galsim.wfirst

### ISSUE THREAD

**Issue by Onoddil** [GalSim-developers/GalSim#1017]
I noticed that ``galsim.wfirst`` does not have a ``thermal_background`` entry for ``R062``. More generally it would be great if any instances where there is information regarding the list of 6 filters (zero points, effective wavelengths, PSF FWHM, what have you) that the R filter could be added to the lists/dicts, to update the WFIRST information with the cycle 7 filter set.

**Comment by matroxel** [comment]
Started implementing additions for R, K filters and other updates to roman specifications under branch #1017. Current branch updates-in-progress will crash due to lack of updates to some underlying roman data files still.

**Comment by matroxel** [comment]
Question for maybe @rmjarvis or @rmandelb about how relative throughput in different bandpasses gets or is intended to get propagated currently. The module has an obscuration parameter that modulates the sky background, which I assumed was intended to match e.g. the pupil mask area. However, the masks are different for the reddest filters, which is accounted for in the effective area throughput curves for the filters. If the filters are (relatively) properly normalized in the interpolation table file, will that also propagate through to an object drawn in H vs F (for example) having different effective brightnesses due to that change in obscuration (and other effects)? Should I modify things to deprecate the separate obscuration parameter, so everything is consistent?

**Comment by matroxel** [comment]
More context - when I rebuild the sky background tables, the obscuration will be taken into account through the effective area curves, making the obscuration parameter moot I think?

**Comment by rmandelb** [comment]
I think that if you have a direct calculation of the effective area, then you indeed should not need the obscuration parameter in order to get the right sky backgrounds.  The code in `roman_backgrounds.py` will need to be modified to reflect this new way of getting the effective area.

The other place obscuration is potentially relevant is in defining the PSF as an obscured Airy with aberrations.  However, the getPSF() method uses the pupil plane images rather than the obscuration parameter for that (so as to include the struts etc. in addition to obscuration).  This is a more accurate calculation than what we would get by plugging in an obscuration and number of struts.

So I think you are right that the obscuration parameter would then be irrelevant, though I am curious if @rmjarvis can come up with other places it is relevant.  I personally find it useful to still include it in `__init__.py` but to indicate in the docstring that it is only there in case useful for approximate calculations, and it's not directly used by any of the `galsim.roman` routines.

**Comment by rmjarvis** [comment]
We definitely shouldn't gratuitously remove it, since it's now part of the official API.  But if none of our routines use it anymore, then I wouldn't worry if it's not hyper accurate.

**Comment by matroxel** [comment]
> We definitely shouldn't gratuitously remove it, since it's now part of the official API. But if none of our routines use it anymore, then I wouldn't worry if it's not hyper accurate.

To keep them used as they are now, my options are to modify the eff area bandpass throughputs (either in the file itself or when read in) to take out the effective area and wavelength-independent obscuration galsim currently uses, then just add it back. This hides the wavelength dependent obscuration. The alternative would be to explicitly change the area/obscuration values to be used as only something to scale things to, rather than being used in the calculations. I think which I prefer depends on the answer to the following (in the sense of whether we can keep new eff area throughput consistent everywhere).

----

Main question: My understanding currently is that the effective throughput drop in eg F/K (or any wavelength dependent drop associated with obscuration or other effects) wouldn't impact the final relative flux of an object drawn in the different filters. Is that a misunderstanding? If it isn't, is there a way to preserve the relative amplitude across bandpasses, as well as wavelength within a bandpass?

**Comment by rmjarvis** [comment]
> To keep them used as they are now, my options are to modify the eff area bandpass throughputs (either in the file itself or when read in) to take out the effective area and wavelength-independent obscuration galsim currently uses, then just add it back.

IMO, there is no reason to do this. I'm completely happy with us not using obscuration anywhere anymore if that's the easier way to get the fluxes right.  No need to do complicated things like this just to preserve some piece of code.  My only point is that once you change everything to be correct, if you find that the obscuration number is no longer used anywhere, don't remove it from `__init__.py`.  Some user might be using it for something else, and we don't want to break their code.

**Comment by rmjarvis** [comment]
Done in #1251
