### ISSUE TITLE
Drawing interpolated image (chromatic) long running time

### ISSUE THREAD

**Issue by ShamlouMehr** [GalSim-developers/GalSim#1039]
Hello Everyone,

I use Galsim module to: 
1.  get the sheared stamps of bulges and disks from another simulation,
2. make the galaxies Chromatic, Convolved, and add WFIRST features to them.
3. and finally, draw the field image.

iMac:
- CPU: 3.2 GHz Intel Core i5
- RAM: 32 GB 1867 MHz DDR3
- iOS: 10.12.6
And:
- python: '2.7.10'
- galsim: '1.4.4'

My code’s running time is strangely long (~ 3 min for 25 galaxies). 
I logged each step and it seems line 236, 
`this_gal.drawImage(bandpass=band, image=stamp, add_to_image=True)` 
is the most time consuming part (~ 0.9sec).
With +100K galaxies the runtime would be ~30 hours.
Attached is a snippet with required files(stamps, catalog, and SEDs).
I appreciate your time and help.

Regards,
Ahmad

[snippet.tar.gz](https://github.com/GalSim-developers/GalSim/files/3394131/snippet.tar.gz)

**Comment by rmjarvis** [comment]
Yep.  Sounds about right.  Chromatic drawing is really slow.  Depending on the profiles involved, it can easily take a few seconds per galaxy, since it basically has to do an integral over wavelength, which isn't particularly fast.  

We have thought about how to speed things up, especially using photon shooting, but they aren't implemented yet.  (cf. #540)

In the meantime, if efficiency is important, you can try simplifying some of your components.  Like use an achromatic PSF.  Depending on what you are trying to study, that might work?

Also, you should really upgrade to the latest release of GalSim, you're several back.  We're on 2.1.5 now.  I don't remember if there were any significant updates to the chromatic algorithms since then, but there were definitely quite a few general efficiency improvements.  So one or more of them could easily be relevant to you.

**Comment by ShamlouMehr** [comment]
Thank you so much!
