### ISSUE TITLE
How to find the file named 'Quick Reference Guide'?

### ISSUE THREAD

**Issue by XJLOVEXXH** [GalSim-developers/GalSim#1114]

**Comment by rmandelb** [comment]
We phased out the Quick Reference Guide at some point in the past few years.  You should instead use the GalSim documentation that lives here: http://galsim-developers.github.io/GalSim/

Is there somewhere in this repo that still refers to the Quick Reference Guide?  If so, we should fix that.

**Comment by rmandelb** [comment]
Answered my question myself: the [wiki](https://github.com/GalSim-developers/GalSim/wiki) still refers to it in a few places, with broken links - may need some other cleanup as well.  I'm happy to take this on in the next couple of days.

**Comment by XJLOVEXXH** [comment]
Thank you very much for answering my question. I read Rowe's paper “ GALSIM:modular galaxy Image simulation toolkit“ to learn about the quick reference guide. If the content of the paper can not be modified, you can indicate the new link next to the old link.
This is just my personal suggestion. I hope it can help you.&nbsp;Thanks again！









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GalSim-developers/GalSim"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月3日(星期三) 晚上8:55
收件人:&nbsp;"GalSim-developers/GalSim"<GalSim@noreply.github.com&gt;;
抄送:&nbsp;"徐小慧"<3491925801@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [GalSim-developers/GalSim] How to find the file named 'Quick Reference Guide'? (#1114)





 
We phased out the Quick Reference Guide at some point in the past few years.  You should instead use the GalSim documentation that lives here: http://galsim-developers.github.io/GalSim/
 
Is there somewhere in this repo that still refers to the Quick Reference Guide?  If so, we should fix that.

**Comment by rmandelb** [comment]
Thanks!  I think it's important to remember that that paper describes a specific GalSim version.  _Many_ aspects of GalSim have evolved since then (features, code structure, installation processes, etc.), not just the documentation.  We have not been updating the paper to describe GalSim evolution since the paper was published, which would be a massive undertaking -- rather, up-to-date documentation describing current GalSim features and documentation can be found [here](http://galsim-developers.github.io/GalSim/_build/html/index.html).  I hope that helps!

**Comment by rmandelb** [comment]
Updated wiki to remove pointers to the quick reference guide.  Closing #1114.
