### ISSUE TITLE
C++ Interface

### ISSUE THREAD

**Issue by JiachuanXu** [GalSim-developers/GalSim#1150]
Hi all, currently I'm developing a project which depends heavily on GalSim and is very time-consuming. I'm thinking about calling the GalSim functions in C++ to make the code faster. However, after searching for a while, I can not find any instructions on how to call those routines in C++. Does anyone have some notes on that? Thanks!

**Comment by rmjarvis** [comment]
Sorry no, we don't really have much documentation about the C++ interface, since it's not our primary user interface.  For instance, we don't make any semantic versioning guarantees that the C++ function signatures will remain the same through minor version updates like we do for the python layer.  (Though we do guarantee they won't change in bugfix releases.)  

As such, we haven't put any effort into making nice documentation for the C++-layer calls.  The only documentation in our main docs related to the C++ layer is [instructions on making the C++-linkable library](http://galsim-developers.github.io/GalSim/_build/html/install_pip.html#installing-the-c-shared-library), which you can do with a special setup.py call, and which is done for you in the conda release.

Beyond that, the best I can do is point you to the [header files](https://github.com/GalSim-developers/GalSim/tree/releases/2.3/include/galsim), which usually have doxygen-style comments giving basic documentation.  But we don't try to compile those into pretty web pages, and I wouldn't be too surprised if there are errors in them.  But it might be enough to get you started.  Especially if you just have a few functions in mind to use.

**Comment by jamesp-epcc** [comment]
I've used this a bit recently. I have a very simple pure C++ test case here that I've been using to test my GPU port of GalSim:

https://github.com/jamesp-epcc/GalSimGPUTest

Just ignore the GPU related stuff and it might be useful.

**Comment by rmjarvis** [comment]
If you would like to checkout branch `cpp_docs`, I added a first pass at documenting the C++ layer code.  To try it out, do the following:
```
git clone https://github.com/GalSim-developers/GalSim.git
cd GalSim/
git checkout cpp_docs
pip install .
./update_docs
open docs/_build/html/cpp.html
```
See also the PR for this update at #1161.
