### ISSUE TITLE
SBProfile::draw : Flux/imscale scaling questionable when full jacobian is provided.

### ISSUE THREAD

**Issue by jecampagne** [GalSim-developers/GalSim#1197]
Hi looking at 
```c++
void SBProfile::draw(ImageView<T> image, double imscale,
                         double* jac, double xoff, double yoff, double flux_ratio) const
```
I wander if there is not a typo concerning the relation of `flux_ratio` and `imscale` notably when 
the jacobian is non null and have non-diag elements, as then 
```c++
invdet *= imscale;
flux_ratio *= std::abs(invdet);
```
In fact all the other jacobian use-case leads to a scaling as `imscale*imscale`.

As I have missed something?
Thanks

**Comment by rmjarvis** [comment]
Yes, you're right about this.  It should be `flux_ratio *= std::abs(invdet * imscale)` to get an extra factor of `imscale`.  Thanks for catching this!

Fortunately, it's a pretty severe edge case.  The normal paths of drawing in GalSim usually end up at this point with imscale=1, so the error doesn't cause any problems (which is probably why no one ever noticed it until now).

I think the only way to hit this case is to:
1. Use `obj.drawReal()` directly rather than the usual `obj.drawImage()`.
2. The object being drawn needs to be transformed with a non-diagonal transformation (either shear or rotation).
3. The image being drawn onto needs to have a non-unit pixel scale (but note that it's not allowed to have a non-PixelScale wcs).

So, it's definitely worth fixing, but it's notable that there is no code in our current test suite that hits this situation, never mind has a test that should have noticed the flux being wrong.  So I suspect it most likely hasn't ever caused an error in anyone's images.  Thank goodness.  :)  

I'll make a PR with the fix shortly.

**Comment by jecampagne** [comment]
I'm glad to have found something valuable.

**Comment by rmjarvis** [comment]
The effect of the Jacobian is transposed in Fourier space.  So that's correct.  J = [[ a, b], [c, d]].  But in Fourier space, you apply J^T.
