### ISSUE TITLE
comma/space delimited PositionD string parsed incorrectly in config layer

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#1299]
According to https://galsim-developers.github.io/GalSim/_build/html/config_values.html#pos-value, I ought to be able to use:

```yaml
...
image:
  image_pos: 123.4, 567.8
```

to set the image position for an object.  But this gets parsed by [_GetPositionValue](https://github.com/GalSim-developers/GalSim/blob/releases/2.5/galsim/config/value.py#L450) to (1.0, 2.0) because strings are indexable.

Reproducer:
```python
import galsim
config = {'image_pos': '123.4, 567.8'}
print(galsim.config.ParseValue(config, 'image_pos', config, galsim.PositionD)[0])
assert galsim.config.ParseValue(config, 'image_pos', config, galsim.PositionD)[0] == galsim.PositionD(123.4, 567.8)
```

**Comment by rmjarvis** [comment]
Interesting.  It seems to only be a problem if the first number is >= 10.  Our unit test for this uses '0.1, 0.2'.  But like you said, it fails if the first number is e.g. 123.4, since trying to parse the first two elements of the string succeeds.

FWIW, a workaround for now is to add $ at the front.
```
config = {'image_pos': '$123.4, 567.8'}
```
