### ISSUE TITLE
Switch python docs from doxygen to Sphinx.

### ISSUE THREAD

**Issue by barnabytprowe** [GalSim-developers/GalSim#160]
This is a question Jim brought up on the code list early on, and I think it's appropriate now to think about it again.

Over to Jim:

"When we have C++ code with Python bindings, there are a couple places we can put the documentation:
- In the Doxygen comments, which come from the C++ header files and describe the C++ interface.
- In the Python docstrings and interactive help, which comes from strings embedded in the Boost.Python wrapper code.

If we really want to do this properly, I think the content in both of those places is slightly different, because they describe slightly different things.  But there's going to be a huge amount of overlap and duplication, and it could be a lot of work to make sure they're both up to date and that important information is present in both places.

Moreover, because Doxygen parses the Python source (rather than inspecting the Python docstrings), there's no way (that I know of) to get the Python interface documentation for wrapped classes into Doxygen.

Overall, while I like Doxygen quite a bit for C++, I wonder whether we'd be better off focusing on the docstrings as the canonical documentation for Python (and maybe not even running Doxygen on Python).  Doxygen makes a point of not actually parsing some of its own markup in Python docstrings, so people aren't forced to make their docstrings look weird when viewed naturally by filling them with Doxygen markup, so I'm not sure we're getting that much from Python-side Doxygen.  And if using Doxygen with Python does mean that we have to put weird markup that disturbs the natural docstrings, do we want that?

I noticed a "doxypy" file that seems to be intended to address some of these problems.  Does it?  If so, could we adapt it to work on the Boost.Python outputs too?

(Barney's note: Joe thought that the answer to this question would be that getting doxypy to do this might be difficult. Probably not impossible.)

I've also heard good things about using Sphinx to document Python, but I don't have any direct experience with it.  Does anyone else?

(Barney's note: no-one really stepped forward on this one, so I guess the answer is no)."

I think it's maybe time to revisit this issue, and get some opinions.  

Currently there are absolutely key pieces of the Python interface that are documented in the C++ wrapping and thus these docstrings are not exposed to doxygen, and thus don't make it into the doxygen docs as far as I can see.  

One option for this might be to rename the C++ wrapper classes and move the current class definitions into pure Python, and thus define the docstrings in .py module files so they are read in (we already add some methods at the Python level for some classes, so this would not represent such a vast change albeit a fairly fundamental one).  Would this work?  Other options may be available, and all of this of course presupposes the desire to continue to use doxygen for Python, which Jim questioned and I think is worth discussing.

Also, as Jim points out, some of the doxygen markup even in the direct Python code looks pretty ugly when viewed naturally (e.g. using `ipython` or `print <thing>.__doc__`) and it's not clear how much of this syntax is necessary given some of the automatic processing that doxygen seems to do.

Points / thoughts / additions / comments for these questions would be welcomed.

**Comment by rmjarvis** [comment]
I updated the title of this to "Switch python docs from doxygen to Sphinx".  I'm convinced that this would be a much nicer form of documentation than what we currently have, which is a bit unwieldy imo.  

Plus, we can even move all the stuff that is currently in the Quick Reference Guide into the main docs, since you can add whatever custom doc pages you want in Sphinx very easily.  Probably some of the wiki pages could also be incorporated.  (I'm particularly thinking of the config layer docs.)  This would be a lot nicer than having multiple locations for documentation for people to look at.  And it would automatically handle all the hyperlinks for us.

I don't particularly have time to do this, but I'm hoping that changing the name of the issue might encourage someone to give it a try.  And I'd be happy to help, since I've done Sphinx docs for TreeCorr, and it's what we're using for Piff, so I have some familiarity with them.

**Comment by ofloveandhate** [comment]
i, too, struggle with maintaining a single set of documentation for a C++ library, and a Python module.  Did your group fully switch to Sphinx?  

My project is [bertini2](https://github.com/bertiniteam/b2/), a polynomial system solver, and I simply can't afford the upkeep on multiple sources of documentation -- in C++ doxygen comments, in markdown pages passed to doxygen, in python docstrings in my C++ boost.python code, in tests for both pieces, ...   I desperately need help getting this all unified.  Any tips from your team are appreciated!  I found your issue by googling "generate documentation for python package built using boost.python"

**Comment by rmjarvis** [comment]
We're actually in the process of ditching boost python (switching to either pybind11 or cffi).  But we haven't switched over to Sphinx yet.  

All our public API is really the Python layer, so I think we're mostly fine with having the public docs only parse the python stuff and use Sphinx for that.  Then leave the doxygen markup in C++ for developer information, but not really worry much about making it look pretty, since users won't care about it.

**Comment by ofloveandhate** [comment]
thanks for the quick response.  i'm trying to try out sphinx now.  

i'm not deeply committed to boost.python, except for my small teamsize.  is your motivation for switching at all the docstrings, or documentation?  one hurdle i am overcoming is that the docstrings in my module using boost.python are compiled in -- so that changing documentation requires recompiling.  i don't like it.  i mean, in C++ doxygen it's the same thing, but...  maybe you know a way around?

**Comment by rmjarvis** [comment]
No, the reason is mostly to make it easier for people to install the code.  By far our biggest source of trouble with installation is the boost dependency.

But, I'll point out that you don't need to do the python documentation in C++ for the boost-wrapped classes.  We add in a lot of documentation in python.  See for instance our Angle class:

https://github.com/GalSim-developers/GalSim/blob/releases/1.4/galsim/angle.py

For the classes, you can just assign to the `__doc__` attribute.  e.g. `Angle.__doc__ = """Some documentation..."""`.  Methods are a little trickier if you care about working in both Python 2 and 3, since the syntax changed.  We have a helper function for that called [`set_func_doc`](https://github.com/GalSim-developers/GalSim/blob/releases/1.4/galsim/utilities.py#L1024).

**Comment by ofloveandhate** [comment]
can i sum up?  

you're moving to sphinx for documentation of your python bindings, but moving generation of the python bindings from C++ from Boost.Python to another binding library such as pybind11 or cffi.

1. you have core c++ code in `src`,
2. and code which generates python bindings in `pysrc`. 
3. the Boost.Python (or other) generated python bindings are not directly exposed to the user, 
4. but instead there's another layer of pure python code which forms the raw bindings into nice modules.  it lives in `GalSim/galsim`.
5. that's where your primary documentation lives -- in the python code that finally wraps the raw bindings and other libraries together.

is that about right?  so that moving to sphinx is orthogonal to the move away from Boost.Python, because you would still parse about the same files in the same folders (`GalSim/galsim`)?

deeply appreciatively, ofloveandhate

**Comment by rmjarvis** [comment]
Yes.  Mostly correct anyway.

The two efforts are definitely orthogonal.  And we haven't actually started any effort to move to Sphinx.  It's just on our wish list for once someone has the time to devote to it.  :)  

Also, some of the classes that we currently expose with boost python *are* the things visible to the user.  E.g. Angle.  Most of the methods and such are defined in C++.  Then in python, we add on some documentation along with a few additional methods that were easier to write in python.  But you'll notice that there is no `class Angle` specification in [angle.py](https://github.com/GalSim-developers/GalSim/blob/releases/1.4/galsim/angle.py).  It's just imports Angle `from ._galsim`, which is the compiled C++ library.

Hope this is helpful for your project.

**Comment by rmjarvis** [comment]
Cheers.  :)

**Comment by rmjarvis** [comment]
Done via #1045
