### ISSUE TITLE
non-trivial weight maps in PSFCorr.cpp

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#341]
Currently the routines in psfcorr.py and PSFCorr.cpp use only a trivial weight / bad pixel map, where the possible options are to use or not use any given pixel.  It should be possible to allow use of a variable weight map across an object.  This isn't the highest priority, but I am opening the issue so I don't forget.

**Comment by rmjarvis** [comment]
I was thinking about this in a different context fairly recently, and I'm not sure that it even makes sense to do HSM with a weight map.  Doesn't adaptive moments pretty much require using all the pixels equally?  I think things get messed up if there are pixels missing.  Even a variable weight map is problematic I think (albeit less so than zero weight pixels).

@rmandelb You must have done something about this for HSC, since you used that for shear measurements, right?  Did you interpolate over bad pixels?  Or do you have an implementation of HSM that can handle variable weights?

**Comment by rmandelb** [comment]
@rmjarvis - for HSC we use the current binary masks (i.e., it's just use/don't use pixel).  That's how we handle the information in the mask plane about bad pixels etc.  We don't attempt any spatially-varying weights beyond that.

I confess I haven't thought too deeply  about the variable weight map idea; it came up in some discussion years ago, and the justification/motivation escapes me now, so I'm fine with closing this issue (especially since nobody else has chimed in to request it).

**Comment by esheldon** [comment]
I agree with Mike, it doesn't make sense to do moments when there are missing pixels.  They technically require infinite support.  The sums would be "unbalanced"

**Comment by rmjarvis** [comment]
OK.  Let's close this then.  If someone decides they want it, they can reopen at that point.
