### ISSUE TITLE
Time series of images

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#542]
On Friday, I had a meeting with Jason Rhodes, Scott Gaudi, and Matthew Penny about how/whether GalSim could be used for some microlensing simulations.  It actually seems that GalSim can do some of what they need already, and there are plans to do some of the other bits during the rest of this calendar year in the context of a planned WFIRST module (more on that later...).  There is one missing piece of the puzzle that I think could be implemented in the context of config pretty easily, but since @rmjarvis is actually the config expert, I wanted to check:

They want to be able to input a catalog that has information about all the objects (position, type, flux, ...) but that includes time-series information.  For example, for objects that are not micro lensed the flux entry might be a NumPy array with entries that are all the same, whereas for a micro lensed object the flux entry will be a NumPy array with entries that differ.  Also, some of the stars will have non-negligible motion due to their own proper motion or parallax, so the positions might be changing.  I was thinking it wouldn't be too hard to make config functionality called TimeSeries (or whatever) that can parse the catalog, pull out all the objects that don't change and render them first (since they are the same in each image), then make a full image for each of the time steps that includes the changed ones.

Does this sound like a feasible way to use config to efficiently make a sequence of images for a catalog with time information in it?

**Comment by rmjarvis** [comment]
I'm pretty sure the config apparatus has enough hooks now to relatively easily make a custom ImageBuilder that would do this.  So I don't think there is any need for something to be added to the GalSim code base.

I'd be happy to help design something if anyone is still interested in this and needs some guidance about how to go about it.  But considering this issue is 5 years old now, I suspect everyone has moved on.  Feel free to reopen or ping me on other channels if you are interested and want my help with this.
