### ISSUE TITLE
Realistic Atmospheres

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#549]
For Great3, we used phosim to get our realistic atmospheric PSF model.

It would be nice to get this functionality natively in GalSim.  cf. Issue #169 where Joerg and Barney did some fact finding for this effort.

**Comment by rmjarvis** [comment]
We are working on this at the DESC hack day.  Mostly, we are adapting code by Srikar Srinath and Jim Chiang to create the wave screen, which we will then turn into a real PSF using the same kind of algorithm as used by OpticalPSF.  We expect this to be slow, since we need to do an fft for every few milliseconds, but we can worry about speed issues later.

**Comment by rmandelb** [comment]
Sounds very cool!  I look forward to seeing what you come up with!

**Comment by rmjarvis** [comment]
Progress: https://confluence.slac.stanford.edu/download/attachments/193769477/hack%20results.pdf?version=1&modificationDate=1446234871000&api=v2

**Comment by jmeyers314** [comment]
Here's what I got on the plane; 
phase screen, PSF snapshot, and cumulative PSF:

![atm](https://cloud.githubusercontent.com/assets/3650485/10862286/a0ca528e-7f70-11e5-9c51-d82938448ad8.gif)

**Comment by rmjarvis** [comment]
Wow. That's awesome!!  Very nice!

**Comment by rmandelb** [comment]
That is super cool!  What's the timing like?

**Comment by jmeyers314** [comment]
>That is super cool! What's the timing like?

The gif is for a 3 second exposure with 30 ms time steps, and a hard-coded physical size of the phase screen (10 m) and its spatial sampling (5 cm); it takes about 3 sec to run on my laptop.

Who knows if these are reasonable choices though; that will take some more work to figure out and should probably depend on gsparams settings.

Definitely faster than I had feared though!

**Comment by mdschneider** [comment]
Great Josh! 

It looks like this is still just one phase screen layer (i.e., one screen at a fixed altitude)? 

Also, is there still an ambiguity about the amplitude of the wavefront perturbations? It looks like you removed a factor of 2 pi.

**Comment by tonytyson** [comment]
Josh:  great!  This nicely resembles high altitude seeing.  On 0.5 - 3 sec timescales about half of the seeing is due to low layers, producing a PSF centroid wander.  This is the main source of PSF ellipticity.

Tony

**Comment by jmeyers314** [comment]
>It looks like this is still just one phase screen layer (i.e., one screen at a fixed altitude)?

I tried to make it 3 screens, though I agree the animation makes it appear like only one.  It's certainly possible there's a bug in the code.

>Also, is there still an ambiguity about the amplitude of the wavefront perturbations? It looks like you removed a factor of 2 pi.

I did remove a factor of 2 pi.  The phase normalization (and other magic numbers) still need vetting.  A few things we can use to check: the expected long-exposure relationship between r0 and FWHM, and AtmosphericPSF vs. Kolmogorov.

**Comment by jmeyers314** [comment]
>This nicely resembles high altitude seeing. On 0.5 - 3 sec timescales about half of the seeing is due to low layers, producing a PSF centroid wander. This is the main source of PSF ellipticity.

Hi @tonytyson.  My initial reaction to the PSF movie above was that the centroid wasn't wandering enough.  I think this may be an FFT artifact related to the periodic nature of the phase screen.  I'll investigate further to see if we can get some more centroid motion.

**Comment by jmeyers314** [comment]
I found the bug that was preventing multiple layers.  Here's the new version:

![a](https://cloud.githubusercontent.com/assets/3650485/10890151/3ccd8558-814b-11e5-8130-8b7949fdcf11.gif)

Next step: track down the magic factors of sqrt(0.00058) and such.

**Comment by tonytyson** [comment]
Josh,
Excellent!  I think you need to add a ground layer screen. The 
simulation is missing some low frequency wander.  What are the altitudes 
of those 3 screens?

Tony

**Comment by rmandelb** [comment]
This looks great, Josh!

**Comment by mdschneider** [comment]
Here's the data on screen altitudes and wind velocities that Steve Kent collected for our hack. I selected 3 altitudes out of this list as nominal suggested values in the docstring. Note there is no correlated data on `r0` values (or equivalently `C_n^2` profiles) as a function of altitude.

Note the wind velocities below are the same for 0-2.5km altitudes. 

The Global Data Assimilation System (GDAS), run by the NOAA National Center for Environmental Prediction (NCEP), puts out various datasets that might be of interest to LSST. GDAS produces "analyses" every six hours, giving a large number of parameters tabulated at 24 altitudes in the atmosphere covering the entire Earth. The following is an example of wind velocities extracted from a file for 2014, Feb 13, 6h UT at the longitude and latitude of CTIO. (Wind velocities are m/s). Altitudes are
approximate.

Long -71, lat -30, kl 1, feet = 0, wind: 0.4 -0.6
Long -71, lat -30, kl 2, feet = 1000, wind: 0.4 -0.9
Long -71, lat -30, kl 3, feet = 2000, wind: 0.4 -0.9
Long -71, lat -30, kl 4, feet = 2500, wind: 0.4 -0.9
Long -71, lat -30, kl 5, feet = 3000, wind: -0.1 -0.4
Long -71, lat -30, kl 6, feet = 5000, wind: -0.3 0.1
Long -71, lat -30, kl 7, feet = 6500, wind: -1.1 0.4
Long -71, lat -30, kl 8, feet = 8000, wind: -1.1 0.1
Long -71, lat -30, kl 9, feet = 10000, wind: -0.3 0.6
Long -71, lat -30, kl 10, feet = 12000, wind: -0.0 0.2
Long -71, lat -30, kl 11, feet = 14000, wind: 0.8 -0.2
Long -71, lat -30, kl 12, feet = 16000, wind: 2.8 -0.1
Long -71, lat -30, kl 13, feet = 18000, wind: 4.6 1.1
Long -71, lat -30, kl 14, feet = 21000, wind: 7.4 2.8
Long -71, lat -30, kl 15, feet = 24000, wind: 10.2 4.7
Long -71, lat -30, kl 16, feet = 27000, wind: 13.3 6.7
Long -71, lat -30, kl 17, feet = 30000, wind: 16.0 8.3
Long -71, lat -30, kl 18, feet = 34000, wind: 17.3 4.7
Long -71, lat -30, kl 19, feet = 39000, wind: 16.1 -1.6
Long -71, lat -30, kl 20, feet = 44000, wind: 12.2 -5.7
Long -71, lat -30, kl 21, feet = 52000, wind: 9.2 -3.0

**Comment by tonytyson** [comment]
OK, which 3?  Wander happens with the 1000 ft layer.  Also dome seeing 
gives wander of comparable amplitude in my experience.

**Comment by jmeyers314** [comment]
> What are the altitudes of those 3 screens?

Hi @tonytyson .  

Since the code is only simulating a single star (for the moment), I believe the altitudes don't enter the mathematics (certainly there are no altitudes amongst the current code input parameters!).

Thinking beyond the current code to simulating more than one star, though, I think we will require the altitudes to figure out how much the projected pupil towards star A overlaps the projected pupil towards star B.  Definitely something to keep in mind as the functionality increases.

As for the lack of image wander, I *think* this might be a problem of missing subharmonics over our 10 meter wide screen.

**Comment by tonytyson** [comment]
Actually no.  Although multi stars have theie motions correlated, 
particularly at low frequency, ALL stars move.  An individual star's 
angular motion relative to a fixed point on the sky (where the telescope 
is tracking) has components to its apparent position coming from each 
screen. The lowest screen (ground layer) causes a low frequency ~1 Hz 
wander (called "wander seeing"). Of course this is easiest for PCA to 
take out since it is highly correlated across a chip.  Turbulent cells 
in higher layers generate speckles, and that component of the star 
centroid motion is at higher frequencies.

A few minutes of staring at the guide star is enough to decide how much 
power in the seeing motion is coming from low vs upper layers.  The 
ratio tends not to change much during a night unless a front comes through.

At very low frequency (~0.1 Hz) the culprit is often bad mirror 
temperature (higher than ambient).  This is separate from the ground layer.

**Comment by jmeyers314** [comment]
@tonytyson , I completely agree that all stars will show image wander; I didn't mean to imply otherwise.

Is the fact that the centroid wander is mostly influenced by the ground layer a statement about the relative turbulence strength in the ground layer (larger C_N^2)?  maybe combined with different typical wind speed?

**Comment by tonytyson** [comment]
More due to power on the scale of telescope aperture plus low altitude. There was a great article by Rene Racine on this years ago.
T

**Comment by jmeyers314** [comment]
2 updates:

First is I have determined that the magic number in Srikar's code, 0.00058, is actually:

```(5 * (24/5 * gamma(6/5))**(5/6) * gamma(11/6) / (6 * pi**(8/3) * gamma(1/6)) / (2 pi)**2```

This makes me smile. :blush:

Second, I added a telescope diameter keyword just to see what the presence of subharmonics, i.e. spatial frequencies smaller than 1/diam, would do to the PSF.  Here's the result:

![a](https://cloud.githubusercontent.com/assets/3650485/11260822/92491058-8e23-11e5-9018-72959ccc845d.gif)

Much more centroid motion!  @tonytyson , does this look more like you would expect, by chance?

**Comment by tonytyson** [comment]
YES!

**Comment by rmandelb** [comment]
(1) How did you figure that out??

(2) This is super cool.

**Comment by gbernstein** [comment]
That is indeed very cool.  How long does this movie take to compute?

**Comment by jmeyers314** [comment]
I tracked the magic number down with a combination of [Roddier (1981)](http://adsabs.harvard.edu/abs/1981PrOpt..19..281R), [Sasiela (1994)](http://adsabs.harvard.edu/abs/1994ewpt.book.....S), and [Noll (1976)](http://adsabs.harvard.edu/abs/1976JOSA...66..207N).  I wouldn't claim I understand all of the intermediate steps at this point, though it would probably be useful to get this written down.  Maybe I'll give that a try over Thanksgiving or winter break...

The compute time for the above is up to a couple minutes now, as I'm enlarging the screen and reducing the sampling scale.  However, the feedback mechanism for both of these adjustments at the moment is "does it make a good movie?" and not "does it make a reasonable integrated PSF?"  So maybe this can be improved somewhat.

**Comment by jmeyers314** [comment]
I’m starting to think more about how to extend AtmosphericPSF to accommodate evaluating multiple PSFs through a single atmosphere at different field angles.  Things to abstract include:

Atmosphere
PhaseScreen
AtmosphericPSF

and potentially something to handle both Fraunhofer and Fresnel propagation, which might just be two different methods of `Atmosphere`.

For a frozen flow phase screen atmosphere, multiple PSFs are relatively straight forward, since it doesn’t matter whether the inner loop is the exposure time integration or the loop over multiple PSFs.  For non-frozen flow, the inner loop needs to be over the multiple PSFs, since otherwise, by the time you’ve finished integrating the first PSF and are ready for the second, the atmosphere has irreversibly changed.  This is clearly difficult to accommodate in the draw-galaxies-into-subimages-one-at-a-time approach we (or at least I) typically use.  Any suggestions?  Should we ditch non-frozen flow phase screens?  Or maybe retain them but with the understanding that PSFs evaluate sequentially in time and not concurrently?

Finally, I'm debating two potential ways to connect `Atmosphere` with `AtmosphericPSF`:

```
 atm = Atmosphere(r0, lam, etc.)
psf1 = atm.getPSF(x1, y1)
psf2 = atm.getPSF(x2, y2)
```

and

```
atm = Atmosphere(r0, lam, etc.)
psf1 = AtmosphericPSF(atm, x1, y1)
psf2 = AtmosphericPSF(atm, x2, y2)
```

I'm leaning toward the second option since it's closer to the way `RealGalaxy` and `RealGalaxyCatalog` interact, though beyond that I don't have a strong preference.  Thoughts?

**Comment by rmjarvis** [comment]
For the API, the former option looks like how we get galaxies from COSMOSCatalog, which are called COSMOSGalaxy in the config layer, but don't actually have a corresponding class in python.  The latter option, as you said, looks like how we make RealGalaxy objects from RealGalaxyCatalog. 

It's not obvious which precedent is more similar to this case.  At the end, an AtmosphericPSF is just an InterpolatedImage.  It doesn't need any extra machinery that would need to be in the AtmosphericPSF class rather than in a method of Atmosphere.  So `atm.getPSF()` would be fine to create and return this object.  

OTOH, you do store `self.phase_generator` currently as an attribute, which would not be natural to tack onto an InterpolatedImage object.  So if that's useful, that might be enough of a reason to have a new class that was implemented as an InterpolatedImage, but had extra information.  `self.atm = atm` I guess in the new refactoring.

We can also just provide both, which is something we have done when we couldn't decide what the "one obvious way" to do something is.  (e.g. `noise.whitenImage(im)` == `im.whitenNoise(noise)`.)  Where there are two obvious ways, I think it's fine to have both implementations.  In this case, `atm.getPSF()` could return an `AtmosphericPSF` object (and be trivially implemented as `return AtmosphericPSF(self, **kwargs)`).  Then users could use whichever API more suited their preferences.

**Comment by rmjarvis** [comment]
For the question about non-frozen flow, it's easy to get repeated realizations of the atmosphere.  Just duplicate the rng at the start of a phase generation.  Then every time through you would get the same series of phase screens.  And I think this is what we want the default behavior to be.  Calling `atm.getPSF()` repeatedly with different positions should get the same realization of the atmosphere but at different locations on the exposure.  

We could also have an option to continue on from the end of the previous time series, but that should at least not be the default behavior, since most of the time, users will be working with a single exposure, which had a single realization of the atmosphere over the exposure time.

I think for the API on this, we want an Atmosphere object to logically define the state of the atmosphere at the start of an exposure.  Then every time you generate a PSF from it, it integrates forward for the given location.

For the implementation, one way to do this would be to have Atmosphere store the rng it was provided on construction as `rng_orig` and use it directly.  Then when making a new PSF, make a copy of it: `rng = rng_orig.duplicate()` and make a fresh AtmosphericPhaseGenerator with the copy.

This has the advantage that an Atmosphere object is logically immutable.  It refers to the atmospheric conditions at a particular moment in time.  So repeated builds of PSFs are deterministic.  

However, I can imagine wanting to build a time series of sequential atmospheric PSFs.  So a couple ideas about an API for that:

1. later_atm = atm.timeSkip(nseconds)  # Skip nseconds into the future
2. next_atm = atm.continuation()  # Get an atmosphere that corresponds to the end of the last PSF generated.

Option 1 preserves the immutability model better, since there would be no internal state that matters for anything the user can see.  But it would require discarding a rather large number of random numbers.  I think that's ok.  Discarding 10^8 values takes much less than 1 second, so it's pretty fast.  (You can cherry-pick the commit where I added the discard function here: df42a810)  But as nseconds gets large relative to the time step, this could become a significant operation.  You'd also have to be careful about figuring out exactly how many values to discard.  We'd want to design a good unit test for this.

Option 2 might be a bit more efficient, but it would require some extra work in the AtmosphericPhaseGenerator class, since we'd want to be able to return the current state and be able to construct a new Atmosphere from that (rather than vice versa).  

All in all, I think I prefer option 1.  I doubt the discarding of rng values will ever be slow enough to care about.

**Comment by jmeyers314** [comment]
>Where there are two obvious ways, I think it's fine to have both implementations.

Sounds good.  I'll aim for that.

**Comment by jmeyers314** [comment]
Returning to non-frozen-flow...  Right, one can reset the rng to make consistent time-integrations.  What I worry about in that case is just speed.  Updating a non-frozen-flow layer requires 2 FFTs per time-step, which get pretty expensive if the layer is large enough to subtend a significant FOV at high altitude.  Frozen-flow is cheaper since you just query a different piece of a static screen at each time step.  My thought was that non-frozen-flow might still be possible if we could avoid recomputing the atmosphere for each PSF.

Here are some estimates for a whole focal plane simulation for LSST:

A 3.5 degree field subtends about 1 km at 15 km altitude.  If we take the resolution to be r0-ish (~15 cm) for now, then the highest screen is ~6000 pixels across.  If we add slop for wind, then 8192 pixels seems natural.  My laptop takes ~6.6 s to FFT an 8192x8192 array using np.fft.  That times 6 layers and 500 time steps (30 ms steps for 15 sec) makes ~5.5 hours overhead for non-frozen-flow that wouldn't be required with frozen-flow.  If the inner loop is PSFs, then we only eat this once though.

Let's estimate the PSF generation too:  the 8.4 m aperture extends 56 15-cm samples.  We want padding for the FFT though, so let's say turning phase into a PSF is a 256x256 FFT, which costs np.fft 1.74 ms.  That times 500 time steps makes 875 ms per PSF, not including time to look up the particular 56x56 patch required for each step.  (BTW, I've been playing with using `InterpolatedImage` and `drawImage` for this, though really I just want a 2D version of `LookupTable`.  Maybe we should make one!)  For 50 objects per arcmin^2 and 9.6 sq. deg., we get 420 hours per LSST focal plane (for just the PSF FFTs).

It's still a research question, of course, what makes a reasonable time step and resolution...

**Comment by rmjarvis** [comment]
> really I just want a 2D version of LookupTable. Maybe we should make one!

This is issue #465.  If you feel motivated, please go ahead and knock that one off.  :)

**Comment by rmjarvis** [comment]
If you can come up with optimizations that let you efficiently compute a whole focal plane worth of atmospheric PSFs at once, I think that would be fantastic.  As far as the API goes, I think something like this would be nice:
```
atm = galsim.Atmosphere(...)
psf_field = atm.generatePSFField(field_radius, grid_size, ...)
psf = psf_field.getPSF(image_pos)
```
where the final psf would be equivalent to 
```
psf = atm.getPSF(image_pos, ...)
```
but more efficient if you'll be doing a lot of these for the same exposure.
