### ISSUE TITLE
Implement Spergel (2010) galaxy profile model

### ISSUE THREAD

**Issue by mdschneider** [GalSim-developers/GalSim#616]
_Motivation:_ We are interested in speeding up the rendering of galaxy images for use in MCMC algorithms to infer galaxy model parameters given a postage stamp image. An alternative galaxy model parameterization may be helpful. 

The slowest part of the prediction of a galaxy image is the convolution with the PSF. Here's a plan for moving the PSF convolution into a pre-computation step, leaving MCMC steps to a simple linear operation for galaxy image predictions,
* [Spergel (2010)](http://iopscience.iop.org/0067-0049/191/1/58/) demonstrates a Sersic-like profile, but with the important feature that it can be Taylor expanded in ellipticity and relative size in such a way that all model parameters are in coefficients of the expansion. Then, the PSF convolution can be pre-computed with each term in the expansion and subsequent model updates are a simple linear operation.
* If the PSF is represented by a Zernike expansion of the exit pupil wavefront, then it’s possible to derive an expansion of the PSF in terms of the Zernike coefficients. Then we can treat PSF models in pre-computation analogous to the Spergel galaxy profile model.
* A dependency graph for these features is [here](https://www.lucidchart.com/publicSegments/view/54822282-b490-4c3c-b314-06a00a004a68/image.png).
* A first step is to implement the functional form from Spergel (2010) as the new `SBSpergel` class, mimicking `SBSersic`.

While GalSim predictions can be sped up by changing `GSParams` settings, we would like to avoid identifying the combination of accuracy and speed tradeoffs for each application if a re-parameterization can be made to work.

Credit for benchmarks and planning: @jmeyers314

**Comment by jmeyers314** [comment]
I think the first part of this issue (drawing the Spergel profile without any Taylor expansion trickery) is almost ready for a PR.  The last remaining question I have is what to do for photon-shooting when nu<0 (in which case the s.b. profile diverges at the origin).  I think this should be possible in principle, but in practice the rejection sampling near the origin ends up in an infinite loop waiting for a deviate smaller than 1/inf.  Any suggestions?

Some other items of note:

- Drawing a nu=-0.6 Spergel profile is about 3x faster than drawing a n=4 Sersic profile, which has about the same shape near the half_light_radius.  A nu=0.5 Spergel takes the same amount of time as an n=1 Sersic (both exponentials).
- I think I found an error in the Spergel(2010) Taylor expansion which when corrected increases the number of terms in the expansion rather significantly, so I'm a bit less optimistic now about precomputing all the convolutions.
- I noticed a couple weeks ago that the Spergel profile is the F.T. of the Moffat profile.  Not sure how to take advantage of that but I thought it was interesting. :)

**Comment by rmjarvis** [comment]
>  in practice the rejection sampling near the origin ends up in an infinite loop waiting for a deviate smaller than 1/inf. Any suggestions?

Where exactly is the problem happening?  Making the `OneDimensionalDeviate`?  Or when drawing from the interval (`Interval::drawWithin`)?  

Anyway, some things you could try:
- Don't go all the way to 0 for the range you provide to the `OneDimensionalDeviate` constructor.  i.e. range[0] = epsilon.  You can figure out what epsilon is appropriate based on `shoot_accuracy`, which dictates how much flux you are allowed to miss when shooting.
- Similarly, you can have the radial function that you give to `OneDimensionalDeviate` flatten off at the origin in a way that misses less than `shoot_accuracy` worth of flux.  In this case, you would want to have range be [ 0, epsilon, shoot_maxr ], since you'll want to let it know that the profile changes non-smoothly at whatever epsilon where you flatten it out.
- Or rather than miss any flux, you can have the central region at r < epsilon have a higher surface brightness such that the total flux there matches what the real profile would have.  Just the s.b. would be discontinuous at r=epsilon (so definitely need to include that value in the `range`).  The appropriate value for epsilon then would be where 2pi int_0^epsilon( r abs(f_true(r) - f_approx(r)) ) < shoot_accuracy.  i.e. the integrated absolute error in the flux.
- You could try to get even more fancy by trying to come up with a function to use at r < epsilon that has the right flux and the right value at r=epsilon, but has f(0) < infinity (and presumably would have a discontinuous first derivative at r=epsilon).  I'm not sure that this is worth it, but you could think about it.

> I noticed a couple weeks ago that the Spergel profile is the F.T. of the Moffat profile. Not sure how to take advantage of that but I thought it was interesting. :)

Aside from using the analytic form in `kValue`, probably not much else to do.  The Moffat class already uses this in reverse.  We used to use a tabulated FT, before I discovered the analytic version -- it was a significant speed up to switch to using `cyl_bessel_k`.

**Comment by jmeyers314** [comment]
>Where exactly is the problem happening? Making the OneDimensionalDeviate? Or when drawing from the interval (Interval::drawWithin)?

Problem was in Interval::drawWithin.  I went ahead and implemented your fancy suggestion above, which turned out to not be too difficult.  Seems to work fine now.

**Comment by rmandelb** [comment]
@jmeyers314 or @mdschneider , should this issue be closed?  Or did you have a further set of work to be done on this issue after the initial PR?

**Comment by jmeyers314** [comment]
>@jmeyers314 or @mdschneider , should this issue be closed? Or did you have a further set of work to be done on this issue after the initial PR?

I had originally envisioned keeping this open until #628 is merged, as the original description by @mdschneider included the series implementation of the Spergel and PSF profiles.  Maybe it's sufficient to just keep 628 open though.

**Comment by rmandelb** [comment]
It's up to you, really, but it seems to me that having two open issues for basically the same body of work isn't necessary.

**Comment by jmeyers314** [comment]
I guess that's fair.  I'm certainly not working in branch 616 anymore.  Closing.
