### ISSUE TITLE
Macports and Anaconda package for Galsim?

### ISSUE THREAD

**Issue by cdeil** [GalSim-developers/GalSim#658]
I just found Galsim, thanks for creating it!
I'm very interested in the methods you describe in the paper and would like to try it out / do some benchmarks for the application I care about.

But don't have much time and it seems galsim installation on my Macbook is non-trivial.

Any chance you can make this work for Macports?
```
port install galsim
```
(I see there's some notes on Macports [here](https://github.com/GalSim-developers/GalSim/blob/releases/1.2/INSTALL.md#ii-mac-osx-108-and-earlier), but I'd prefer not to have to install `tmv-cpp` manually and then learn how to pass the right options to `scons`. If you contribute Portfiles for `tmv-cpp` and `galsim` and put yourself as maintainer I'm sure they will be accepted by Macports)

Alternatively, I have conda, so if you could make this work, running galsim would also be easy for me:
```
conda install galsim
```

**Comment by rmandelb** [comment]
Hi and welcome,

If you look in the INSTALL.md file, you'll see that you can get GalSim on one package manager for Mac (fink), and you can also download a tar ball containing Portfiles for both TMV and GalSim in order to carry out an installation of GalSim plus all dependencies using Macports:

https://github.com/GalSim-developers/GalSim/blob/master/devel/ports.tar.gz

If you follow the instructions to use those portfiles as described in INSTALL.md, it should install everything for you.  (You don't have to separately install TMV.)

To my knowledge, installation via fink has been used successfully by quite a few people, and if you don't have fink on your system it is very quick to install (I know from personal experience, having gotten it solely for the purpose of trying out GalSim installation via fink!).  The port files have been less used, with one person that I know of reporting success and another currently having some issues that we're digging into (it's still not clear to me if that may be a peculiarity of his system or what, since that's a work in progress).

**Comment by rmjarvis** [comment]
Assuming Rachel's response here has resolved the issue.  Closing.

**Comment by dkirkby** [comment]
I am re-opening this issue to see what the prospects might be for getting GalSim packaged for distribution via conda and/or pip.  The reason I am asking is that the DESI spectrograph simulation (currently under development in [desisim](https://github.com/desihub/desisim) and [specsim](http://specsim.readthedocs.org)) needs to simulate psf-convolved galaxy shapes. This would be straightforward using GalSim, but my collaborators are understandably reluctant (desihub/desisim#77) to add GalSim as a required dependency for running our simulations because it is not installable with any of the standard python package managers.

I am really hoping to avoid re-implementing the necessary parts of GalSim for DESI and wondering what the chances are of re-visiting the GalSim distribution strategy?

**Comment by rmandelb** [comment]
The fact that it's installable with fink is not sufficient?  Do your collaborators care primarily about installation for OSX, Linux, both, ...?

**Comment by dkirkby** [comment]
No, fink is not a complete solution even for Mac users (I don't use it). We would need a relatively straightforward install and upgrade process at NERSC, for example.  We recently asked the Utah Center for High-Performance Computing to install GalSim for some eBOSS work, but it turned out to be quite onerous (and led to #704).

**Comment by rmjarvis** [comment]
I have a long term plan to get GalSim installable via pip, but it's a pretty huge job, since I'm pretty sure boost python won't work with pip.  I've had very good experience using cfft, so I'm inclined to switch to that, but it will require a huge middle-layer refactoring.  I'm willing to do it, but it will take some time that I haven't had yet.

**Comment by dkirkby** [comment]
Thanks for the update Mike.  Its definitely a big job, but at least its good to know that you are thinking about it.  It doesn't sound likely that you will find enough time for this within the next 6 months (but please correct me if I'm wrong), so we may need to implement something standalone for DESI, at least as a short-term solution.

**Comment by rmjarvis** [comment]
You're not the only group to want this by any stretch, so it might happen within 6 months.  But I don't foresee a large hunk of time coming available very soon, so probably best to plan a contingency for the short term.

**Comment by rmjarvis** [comment]
Superseded by #794
