### ISSUE TITLE
Separable ChromaticObject with null SED at bandpass effective wavelength is undrawable.

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#680]
Drawing separable `ChromaticObject`s currently works by first drawing the achromatic object at the effective wavelength of the filter in question, and then scaling this image by the wavelength integral of bandpass * SED.  This fails, however, if the value of the SED is zero at the effective wavelength of the filter, a situation that probably doesn't occur too often with realistic spectra/filters but can occur (and just did for my office-mate!) for contrived tophat filters and SEDs.

One possible solution would be to search for a fiducial wavelength (probably still starting at the filter effective wavelength, or maybe at the midpoint between the filter blue/red edges) for which the SED has non-zero flux.

**Comment by rmandelb** [comment]
Tell your office-mate not be so contrived!

Just kidding.  I think your solution is reasonable.  I would imagine it could be fixed by taking this
```
        # setup output image (semi-arbitrarily using the bandpass effective wavelength)
        prof0 = self.evaluateAtWavelength(bandpass.effective_wavelength)
```
and doing something slightly more complicated to ensure that a reasonable wavelength with nonzero flux is chosen, so that later on you can do the rescaling by ```multiplier``` without a problem.

**Comment by rmandelb** [comment]
Can close this now?

**Comment by jmeyers314** [comment]
Right.  Yes, thanks.
