### ISSUE TITLE
clearly document that x->col and y->row

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#682]
In C/C++ and numpy the order of indexing is
```
image[row, col]
```
which by convention is understood as "y, x".  I think this ordering is also followed by galsim Image objects since you can get a direct view as a numpy array.

A number of galsim functions (eg. shift()) take a tuple of arguments listed in the docs as (x,y) but it isn't clear if that is meant to follow the same ordering as images (row,col) or be equivalent to (col, row).  By word of mouth I have heard it is indeed (col,row), so the (row->y)  (col->x) relation holds, it is just the arguments are given in reverse.

Since this ordering is reverse of C/C++/python/galsim.Image conventions I think it is worth a big notice in the docs up front.  Sorry if this is clearly stated and I just missed it.

**Comment by esheldon** [comment]
As a correlary to this, it might be useful to provide keyword arguments that make the meaning explicit, e.g
```
shift(drow = drow, dcol=dcol)
```

**Comment by rmjarvis** [comment]
The (x,y) notation in GalSim matches that of ds9, SExtractor, SAOImage, etc.  This is the standard way of referring to positions on an astronomical image.

We do document in the `Image` class docstring that this is backwards of how numpy accesses elements:
```
    The `array` attribute is a NumPy array of the Image's pixels.  The individual elements in the
    array attribute are accessed as `image.array[y,x]`, matching the standard NumPy convention,
    while the Image class's own accessor uses `(x,y)`.
```
We could probably add a bit more explanation of this difference, but I definitely do not want to use the terms `drow` and `dcol` for this.  That IMO would only serve to add to the confusion.  

The API should insulate the user from caring about how x and y are stored internally.  That's why we currently have the above explanation in our description of the `array` attribute, since that's where the user is accessing the implementation, so they need to know.  At other points in the code, (x,y) should be abstractions that the code will implement however is appropriate.

**Comment by esheldon** [comment]
Right, I understand this.

What I'm asking is for is a big up-front explanation at the very front of the galsim docs saying that everywhere a user sees x listed in the code or documentation, they can safely assume this means "column in the image" and that y means "row in the image" so they can do the translation in their head between the different ordering as appropriate.
