### ISSUE TITLE
COSMOS galaxies built with _makeSingleGalaxy always have index attribute set to zero

### ISSUE THREAD

**Issue by beckermr** [GalSim-developers/GalSim#694]
COSMOS galaxies made with _makeSingleGalaxy always have their index set to zero. 

I think in order to preserve the static methods, the index will need to be passed out of this function 

https://github.com/GalSim-developers/GalSim/blob/releases/1.3/galsim/scene.py#L502

to the real galaxy maker and added there.

@mjarvis: Is this fixed #691? If not, is there a bug in the truth data feature you are adding? I was using this feature in my sims and getting all zero indexes.

**Comment by rmjarvis** [comment]
OK.  The gal.index attribute isn't documented functionality, so I'm not sure it counts as a but to not have it set correctly in some circumstances.  But it's an easy enough fix to do so.  Commit 6a7fc34 on branch #691.

BTW, there wasn't any bug in the truth values for cgc, since this wasn't where it was getting the index numbers.

**Comment by beckermr** [comment]
Good point and thanks for the fix!

**Comment by beckermr** [comment]
I won't be bothered if you decide not to support this. Def not a bug, more a feature request as you say.

**Comment by rmjarvis** [comment]
Sorry.  This should work: 8bfecb0

I actually did some testing this time before committing. :-S
