### ISSUE TITLE
drawImage docstring confusion

### ISSUE THREAD

**Issue by danielsf** [GalSim-developers/GalSim#700]
I am finding myself tripping over the following paragraph from the docstring for GSObject.drawImage:

"Note that if you provide an `image` parameter, it is the image onto which the profile will be drawn.  The provided image *will be modified*.  A reference to the same image is also returned to provide parallel return behavior to when `image` is `None` (described above)."

My naive interpretation of this is that the following code should produce a fits file ('test_second_source.fits') with two sources on it

```
import galsim
import numpy

scale=0.2

blankImage = galsim.Image(int(200),int(200))

obj = galsim.Sersic(n=4, half_light_radius=0.14, flux=70000.0)
obj = obj.shear(q=0.75, beta=0.3*galsim.radians)
image1 = obj.drawImage(scale=scale, method='phot',image=blankImage)
image1.write('test_first_source.fits')


obj2 = galsim.Sersic(n=4, half_light_radius=0.14, flux=70000.0)
obj2 = obj2.shear(q=0.75, beta=0.3*galsim.radians)
dx = 0.25*(image1.xmax-image1.xmin)*scale
obj2=obj2.shift(dx,0.0)
image1 = obj2.drawImage(scale=scale,method='phot',image=image1)

image1.write('test_second_source.fits')
```
but that is not what happens.  test_second_source.fits only has one source in it.

Can someone please help me understand what I am doing wrong/not understanding?

Thanks.

**Comment by rmandelb** [comment]
Hi - the issue here is that drawImage has an ```add_to_image``` kwarg that determines whether the new information is (a) added to the existing image (```add_to_image=True```) or (b) whether the image that is provided is zeroed out before drawing (if False).  The default is False.  So the words in the docstring about modifying the image mean that the provided image either gets wiped clean and drawn into, or added to, and the former behavior is the default.  But either way it's modified.

**Comment by danielsf** [comment]
Thank you.
