### ISSUE TITLE
Bandpass.thin() destroys zeropoint state

### ISSUE THREAD

**Issue by mdschneider** [GalSim-developers/GalSim#711]
I tried creating a `Bandpass` object from a lookup table as follows:

    bp = galsim.Bandpass(table)
    bp = bp.withZeroPoint(zeropoint='AB', effective_diameter=6.4, exptime=15)

**Comment by rmandelb** [comment]
I see what you mean.  The thin() method returns a new Bandpass object and doesn't transfer over the information about the desired zeropoint.  

I think the fix could be as simple as changing the initialization of the new Bandpass to transfer over the zeropoint information from the original one.  @jmeyers314 , is that correct, or is it more complicated than that?

**Comment by rmandelb** [comment]
(Also should include this in a unit test.)

**Comment by jmeyers314** [comment]
>I think the fix could be as simple as changing the initialization of the new Bandpass to transfer over the zeropoint information from the original one. 

I think that sounds right, though I'd want to think a bit about whether or not a zeropoint should/could be recomputed using the thinned representation of the Bandpass.  Would it be worth keeping the "more accurate" zeropoint from the more finely sampled pre-thinned Bandpass even if this is different than what one would have computed on the post-thinned Bandpass, for instance?

**Comment by rmandelb** [comment]
Hmmmm.  I think my answer will depend on the following: If you thin a typical bandpass using the defaults for how much to thin, how much do zero points typically change after recomputing with the thinned bandpass?

**Comment by rmandelb** [comment]
Sorry for the delay, @mdschneider , this fell off my stack.  I just created a branch with a fix for this.  By default it gives the thinned bandpass the same zeropoint as the original.  The justification for this choice is that for the default thinning kwargs and typical optical bandpasses, recalculating the zeropoint with the thinned bandpass results in a change in zeropoint that is of order 10^-6.  However, I also added a keyword that people can use to tell it to forget about the bandpass.  This seemed unnecessary to me at first (because I figured that if someone really cares to recalculate, maybe because they thinned more aggressively, they could just recalculate the zeropoint themselves after thinning - it doesn't really matter that it's temporarily assigned a wrong one).  But then I realized it's an opportunity to explicitly flag the fact that the old zeropoint is not technically the correct one, which otherwise people might overlook.

@rmjarvis and @jmeyers314 - I made the new branch off of #549, so will wait on a PR until that one is merged.  But I've finished the work on here, so it's all ready to go.

**Comment by jmeyers314** [comment]
Looks good to me @rmandelb !

**Comment by rmandelb** [comment]
Glad to hear it.  Will open the PR now so that hopefully @rmjarvis and/or @mdschneider can check it out easily.

**Comment by rmandelb** [comment]
Closing #711.
