### ISSUE TITLE
CCD noise model

### ISSUE THREAD

**Issue by dkirkby** [GalSim-developers/GalSim#712]
I was confused by the ``electrons per ADU`` units of the CCDNoise gain parameter since I normally think of an amplifier gain as output / input, so I wanted to check how the gain is actually used in the code.  I couldn't find the relevant equation anywhere in the docs, but I eventually found this in `Noise.h`:
```
        double getVariance() const 
        {
            if (_gain > 0) return (_sky_level + _read_noise*_read_noise) / _gain;
            else return _read_noise * _read_noise;
        }
```
If the piece in parentheses is a variance in `electrons**2`, shouldn't it be divided by `gain**2` here?

**Comment by rmjarvis** [comment]
Not quite.  Although, you're right that this line is wrong.  The correct formula is
```
sky_level / gain + (read_noise / gain)**2
```
And I agree with you about the definition of gain being weird.  ADU/e- would be much more natural, but e-/ADU is the standard definition for astronomy detectors.  Or CCDs at least.  cf. http://www.mirametrics.com/tech_note_ccdgain.htm

Unfortunately, it looks like our unit test of this function just checked that the output was this formula, rather than adding noise to an image and checking that the variance was right (or close).  I just did that, and the variance is indeed close to the formula I gave, but not close to `ccd_noise.getVariance()`.  I'll fix this and update the unit test.

**Comment by rmjarvis** [comment]
BTW, the link I gave above has this quote: 

> Note: This use of the term "gain" is in the opposite sense to the way a circuit designer would use the term since, in electronic design, gain is considered to be an increase in the number of output units compared with the number of input units.

As usual, astronomers do everything backwards.  :)

**Comment by dkirkby** [comment]
Thanks for the reference Mike.

Your formula assumes that `sky_level` is in ADU/pixel, but the docstring says it is in electrons/pixel:
```
@param sky_level    The sky level in electrons per pixel that was originally in the input
                    image, but which is taken to have already been subtracted off.
                    [default: 0.]
```
In this case, I believe my formula is still correct:
```
variance = (sky_level + read_noise ** 2) / (gain ** 2)
```

**Comment by rmjarvis** [comment]
Ah, yes.  That seems to be another error.  The code assumes sky_level is in ADU/pixel (which is actually how it is usually given, so I think we want to keep that). The doc string is wrong here.  But you're right, if we did what the doc says, your formula is correct.  I'll fix the doc string about this too.

**Comment by dkirkby** [comment]
To add to the confusion, demo3 uses the name `sky_level` for a surface brightness in ADU / arcsec^2, instead of ADU / pixel, and claims a read_noise in ADU / pixel, but passes it to CCDNoise with gain > 0, implying a read noise in electrons / pixel:
```
    sky_level = 2.5e4      # ADU / arcsec^2
    gain = 1.7             # photons / ADU
    read_noise = 0.3       # ADU / pixel
    ...
    image.addNoise(galsim.CCDNoise(rng, gain=gain, read_noise=read_noise))
```

**Comment by rmjarvis** [comment]
Yep.  Looks like some of those annotations are wrong too.  :P  I'll clean this up and ping you when I think I have it all right.
