### ISSUE TITLE
shift() does not seem to shift the image by the expected amount

### ISSUE THREAD

**Issue by dstndstn** [GalSim-developers/GalSim#719]
Hi,

I thought I could shift a model by a certain distance in pixels using the .shift(dx=...) function, but when I render out the object and measure its centroid, the centroid is moving at a different rate... so is the shift() not in pixels?  It doesn't look like any pixel scale I recognize if it were in arcseconds or something.  What am I missing?

Example code and plot attached.  I would have expected the slope to be 1, but it looks like it's about 1.18.

![shift](https://cloud.githubusercontent.com/assets/1065981/13583290/7741bd6c-e47e-11e5-822e-97d9d20f6b42.png)

[shift.py.txt](https://github.com/GalSim-developers/GalSim/files/162090/shift.py.txt)
Thanks,
--dustin

**Comment by rmandelb** [comment]
Per the docstring for ```shift```: ```The shift coordinates here are sky coordinates.``` (and read onward from there for more details)

If you want to shift in pixel coordinates, you should instead use the ```offset``` kwarg of ```drawImage```.

**Comment by rmandelb** [comment]
...and I should have said, here's my interpretation of what's happening with your script:

- let's say dx=1, i.e., you shift by 1 in sky coordinates.
- since you did not set a scale for the image, it's 1 arcsec/pixel, i.e., the above shift is a pixel.
- but since you use drawImage without specifying a drawing method, it's convolving with a top-hat pixel response before drawing.
- so basically you have drawn a convolution of "Gaussian shifted horizontally by 1" and "top-hat pixel response function".  I'm not sure that should shift over at a rate of 1.  You could check by removing the pixel convolution before drawing (using ```method='no_pixel'```), and seeing what this looks like.  In that case I would expect a slope of 1.

**Comment by dstndstn** [comment]
Okay, thank you very much.  Sorry for the noise!

​

**Comment by rmandelb** [comment]
Oh duh, stupid mistake in above.  See edited version.

**Comment by dstndstn** [comment]
Aha!, thanks for the sleuthing.
