### ISSUE TITLE
Error while making some chromatic galaxies

### ISSUE THREAD

**Issue by arunkannawadi** [GalSim-developers/GalSim#745]
While trying to make chromatic galaxies from the COSMOS catalog, a few cases seem to try accessing wavelengths well beyond the range of SEDs. For example, the following code:

`import galsim`
`cc = galsim.COSMOSCatalog(use_real=False)`
`gal = cc.makeGalaxy(30105,chromatic=True)`

throws an error message:
` ValueError: Requested wavelength (400.0) is bluer than blue_limit (499.543110609) `

@jmeyers314 , do you know anything about this?

**Comment by jmeyers314** [comment]
Interesting.  I think there are a couple of things going on here.  The SED is basically reporting that it isn't defined where you need it to be defined in order to compute a flux through a Bandpass.

Part of this may be that the Bandpass in question extends down to 400 nm, even though the bulk of the throughput doesn't actually start until ~700 nm.  So using the .truncate method [here](https://github.com/GalSim-developers/GalSim/blob/master/galsim/scene.py#L577) might be appropriate.  Actually, I'd probably just pre-thin and truncate this file (documenting what you do in its header) in the share directory so this doesn't need to happen when running scene.py.

More critically though, the SEDs aren't being read in right.  They're missing a `wave_type='ang'` kwarg [here](https://github.com/GalSim-developers/GalSim/blob/master/galsim/scene.py#L586) and below.  I probably should have caught this in an earlier review, sorry!  What you've effectively discovered is that GalSim refuses to compute the F814 flux for a z=26 elliptical spectrum, which I don't think is that surprising.

Finally, we should probably update the bandpass and sed files in the share dir so that they use the newer version of .thin().  I remembered to do this for examples/data/, but not for share.

**Comment by rmandelb** [comment]
Thanks for looking into this Josh.

> Actually, I'd probably just pre-thin and truncate this file

Regarding the bandpass, I think we'd prefer to keep it as-is in share.  Right now the bandpasses get read in with proper zero points etc. by the ```galsim.wfirst.getBandpasses``` routine, which also thins them according to a user-specified value of ```thin_err```.  We'd like to make it possible for people to modify ```thin_err```, which would require the full, non-thinned bandpasses to be stored.

But it sounds like you recommend that we use the ```truncate``` method in ```getBandpasses``` too?  Right now we leave that up to the user, but perhaps we should make a kwarg for that (and have it be True by default).

> More critically though, the SEDs aren't being read in right. They're missing a wave_type='ang' kwarg 
> here and below.

*headdesk*
That's bad.  I was trying to think how I might not have caught that, and I think I know why: when using that functionality, I mostly tested that flux normalization is OK when compared to HST - i.e., that I could say "this object has this SED and magnitude in I band" - and then I would draw it in I band, so the flux came out fine by construction.

> Finally, we should probably update the bandpass and sed files in the share dir so that they use the 
> newer version of .thin()

Does it really make sense to store them after thinning?  I feel like that gives the user less choice about how much to thin.

**Comment by jmeyers314** [comment]
>Regarding the bandpass, I think we'd prefer to keep it as-is in share. Right now the bandpasses get read in with proper zero points etc. by the galsim.wfirst.getBandpasses routine, which also thins them according to a user-specified value of thin_err. We'd like to make it possible for people to modify thin_err, which would require the full, non-thinned bandpasses to be stored.

Ah, okay.  I was mostly just looking at this line: https://github.com/GalSim-developers/GalSim/blob/master/galsim/scene.py#L577 which hard codes a call to `.thin()` that could be avoided by prethinning a file.  I guess this just gets done one time for the catalog, and then reused for each galaxy though, so maybe it's not so much overhead.  You may want to take a look at a plot of the throughput function though to see if you think truncation (or thinning with preserve_range=False) makes sense.  The old `.thin()` algorithm would do some trimming of leading and trailing wavelengths by default, but we found that this created some (small) inaccuracies for certain synthetic photomety calcs, so the new `.thin()` now preserves leading and trailing wavelengths by default.

Updating `wfirst.getBandpasses` to pass through the new thinning kwargs (), and also optionally truncating is probably a reasonable thing to do.

>I was trying to think how I might not have caught that, and I think I know why: when using that functionality, I mostly tested that flux normalization is OK when compared to HST - i.e., that I could say "this object has this SED and magnitude in I band" - and then I would draw it in I band, so the flux came out fine by construction.

Yeah, I think it's hard to figure out a good unit test for this.  You're certainly not the only one I've seen make this mistake though.  I'm pretty sure I've done it too.  It makes me think that maybe there shouldn't be a default value of `wave_type`, and instead we just always require this argument be set explicitly by the user?  Same with `flux_type` and `wave_type` for Bandpasses?

>Does it really make sense to store them after thinning? I feel like that gives the user less choice about how much to thin.

Yeah, that's true.  It doesn't matter so much for the examples, I suppose, but for more "official" uses keeping the unthinned version is probably the right thing to do.  We could provide both, I suppose, with clearly marked filenames.

**Comment by rmandelb** [comment]
> It makes me think that maybe there shouldn't be a default value of wave_type, and instead we just 
> always require this argument be set explicitly by the user? Same with flux_type and wave_type for 
> Bandpasses?

Interesting idea.  It certainly would avoid the problem of people accidentally using the default when they shouldn't, and force them to check.  @rmjarvis , what do you think?

@jmeyers314 , regarding the other stuff you mentioned:
- I like the idea of providing both the thinned and un-thinned versions for SEDs and bandpasses.
- Updating ```wfirst.getBandpasses``` to pass through the new thinning kwargs + optionally truncating makes sense to me.
- Obviously I need to fix the bug in scene.py (units bug).
- I will check into how the thinning/truncation is done there, and consider using one of the options you mentioned.

I'm volunteering to do this (possibly as early as today), but you're welcome to take on any bits of it that you like.  Also I added this issue to the v1.4 milestone because it would be nice if the newly updated COSMOSCatalog functionality was also free of this bug.

**Comment by rmjarvis** [comment]
> @rmjarvis , what do you think?

Fine with me.

**Comment by rmandelb** [comment]
My only concern is what is this going to do to people's existing code?  What are your thoughts on that?

**Comment by jmeyers314** [comment]
>My only concern is what is this going to do to people's existing code? What are your thoughts on that?

I think this is an acceptable backwards incompatibility.  For those who currently explicitly specify `wave_type` and `flux_type`, everything will continue to work.  For those who currently rely on the default, they'll presumably get an informative error message letting them know these kwargs are now required.  The important thing, I think, is that these changes shouldn't lead to older code failing silently.

**Comment by rmandelb** [comment]
Closing #745.
