### ISSUE TITLE
yaml in unit tests

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#768]
@arunkannawadi just pointed out that the unit tests now require pyyaml, which was not the case in the past.  

I notice that  in ```test_config_value.py```, the yaml parts of the tests are skipped if the yaml module cannot be imported (with a comment mentioning that this is done because it's an optional dependency).  However, it seems this is not being done uniformly.  @arunkannawadi - can you point out which test it's failing on?

The question is whether we should fix those unit tests so they skip the yaml part if it cannot be imported, or make pyyaml required.  I am in favor of the former.

**Comment by arunkannawadi** [comment]
Here is the relevant part of the output:
```
Traceback (most recent call last):
  File "/opt/python27/lib/python2.7/site-packages/nose-1.3.0-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/akannawa/python_modules/GalSim-releases-1.2/tests/galsim_test_helpers.py", line 412, in f2
    result = f(*args, **kwargs)
  File "/home/akannawa/python_modules/GalSim-releases-1.2/tests/test_catalog.py", line 88, in test_basic_dict
    d = galsim.Dict(dir='config_input', file_name='dict.yaml')
  File "/home/akannawa/usr/lib/python2.7/dist-packages/galsim/catalog.py", line 283, in __init__
    import yaml
ImportError: No module named yaml
```

**Comment by rmjarvis** [comment]
I'm pretty sure this was also the case in version 1.3, although not in 1.2.  

I'm probably in favor of just making pyyaml a recommended dependency, although pointing out that you don't technically need it if you don't ever use the config stuff.  Especially with the recent changes to improve the config parsing layer in v1.4 and the updated tutorial descriptions, we imply that this is a recommended way to use GalSim.  Seems a bit weird to have people discover this dependency then rather than when they are first installing GalSim.

But it's not hard to change the unit test to catch an ImportError.  I'll do that on master regardless of what people think about the dependency question.

**Comment by rmjarvis** [comment]
Done on master.

**Comment by rmandelb** [comment]
Thanks for doing that, Mike.

I'm fine with making it recommended and pointing out you don't technically need it if you don't use config.  If you could please insert this with whatever wording you think is best, I would appreciate it.

**Comment by rmjarvis** [comment]
Done.  See 711475e

**Comment by rmandelb** [comment]
Thanks Mike.
