### ISSUE TITLE
AEGIS catalog

### ISSUE THREAD

**Issue by jmeyers314** [GalSim-developers/GalSim#770]
This issue is to finalize and add the HST F606 and F814 AEGIS catalog that @sowmyakth has been assembling into GalSim (mentioned in #551).  Our goals for this catalog are to 1) be compatible with the existing GalSim COSMOS catalogs, and 2) be a source catalog for ChromaticRealGalaxy #640.  

We're also hoping to add to the repository the python scripts that @sowmyakth has been developing for turning HST images into catalogs (based off of a variety of scripts from @rmandelb), which should be generic enough to be useful for adding other HST surveys down the line (e.g. CANDELS).

First things first though: can @rmandelb or @rmjarvis please add @sowmyakth to the GalSim-developers team?

**Comment by rmandelb** [comment]
Glad to see this!  How is it going?  Need any further help translating / replacing my scripts?

**Comment by sowmyakth** [comment]
I'm almost done. I'm working now on getting the required files for galsim. In the selection.fits why do you save the distance to the nearest replaced pixel and the average around this pixel?

**Comment by rmandelb** [comment]
Because we wanted to be able to select (+remove if necessary) galaxies that were more like to have been blended with another nearby object, or objects with sky subtraction errors or failed blends.  Both of those quantities can be used for that purpose.

**Comment by sowmyakth** [comment]
@rmandelb For the file containing correlated noise field is what was reasoning for naming it acs_I_unrot_sci_20_cf.fits? What is sci_20? 
For AEGIS I took a blank region, got the correlated noise using galsim.CorrelatedNoise and drew the image. Is this the right method?

**Comment by rmandelb** [comment]
Hi Sowmya -

The name of this file has its origins inside the brain of @barnabytprowe :) but you can see more about it here: https://github.com/GalSim-developers/GalSim/pull/358 where he describes the process of producing those files.  The relevant scripts are in the GalSim repo, devel/external/hst/ if you want to check it out and make sure you do something comparable for AEGIS?

For COSMOS, he used more than one blank field, partly to beat down the noise in estimating the noise correlation function, and partly because the correlated noise varies somewhat as a function of position, so he took the average to be representative.  I would think that AEGIS is small enough that you wouldn't need as many blank fields as he used (indeed it would be hard to find so many) but you might want more than one, since the noise correlation function estimated from one field would be noisy.  Can you see how noisy your CF image is?

My guess is that the ```unrot_sci``` bit is because he's using the COSMOS **unrot**ated mosaics that were produced for weak lensing **sci**ence.  I don't know about the 20 but I just realized it's not his fault; according to the docstring on his script, the mosaics he got all have ```unrot_sci_20``` in the filename.  So I guess it's Anton K's fault.

**Comment by barnabytprowe** [comment]
Yup definitely Anton's fault :)  And @rmandelb your other deductions regarding the filename were spot on.

@sowmyakth I guess the only procedure I can suggest to tell whether or not you have compiled enough empty fields is to check how quickly the correlation function (CF) converges to a stable pattern as you average over the CFs adding successive fields.  You could also just look at the standard deviation in the CF values across your six images (I'd probably advocate getting a few more too) to estimate how many you will need to co-add to reach a certain fractional uncertainty across the CF.

I'd probably advocate at least 16 or so, sampled, if possible, from an approximate 4x4 grid in the telescope field of view to cover the varying distortions.  But how many you need also depends on how large the fields were to start with, as smaller fields will yield noisier CF estimates.  You will see in the pull request #358 that Rachel referenced above that I went way beyond that for COSMOS and got as far as 92 fields before I finally got bored!  That was possibly overkill :)

**Comment by barnabytprowe** [comment]
oooh digging through the public ACS data for COSMOS I think that 20 might refer to a version 2.0 of the processing pipeline... although I believe only v1.3 images were made public through the IPAC portal, these were labelled `*_13.fits` and v1.2 were `*_12.fits`.  The version 2.0 process must have been something that Alexie Leauthaud had access to but was never made public via IPAC.

**Comment by barnabytprowe** [comment]
One final thing (then I'll crawl back under my rock) - I am quite encouraged looking at https://github.com/sowmyakth/true_gal_colors/blob/master/check_empty_regions.ipynb that you are already getting some way down into the noise, but I was struck that there was a tendency to have input noise images that were a little longer in the x direction than in the y.   This will mean that the uncertainty in the CF in the vertical direction will necessarily be higher than the horizontal, and this is the sort of quadrupole asymmetry which gives pause for thought where shear measurements are concerned.

If you are able to find any more noise fields @sowmyakth , some long thin ones to balance the wide ones out a little bit would not hurt!

**Comment by rmandelb** [comment]
You're welcome to stay out from under the rock for a while.  :)

**Comment by sowmyakth** [comment]
Thanks @rmandelb , @barnabytprowe for the help. I redid everything with 16 empty regions. I measured the standard deviation of central value with bootstrapping, for different number of empty fields. It looks like this
![screen shot 2016-08-02 at 7 39 56 pm](https://cloud.githubusercontent.com/assets/13785537/17352201/8df022f8-58e9-11e6-8338-b49993e5b2ff.png)
I think it looks good enough.

**Comment by rmandelb** [comment]
Yes, looks like you're converging!

**Comment by sowmyakth** [comment]
The AEGIS 2 filter catalog is ready, it's about 3.2 GB and is currently on a drive at SLAC. The catalog  can be accessed with galsim.RealGalaxyCatalog( ). The script has a README file explaining how to run it. I've also made a separate [Overleaf document](https://www.overleaf.com/read/krbzsccfdbpm) explaining the procedure and the catalog. What would be a good spot to upload the catalog files and the document?

**Comment by rmandelb** [comment]
Hi @sowmyakth , that's great.  A few comments / suggestions:

- It would be great if we can put the catalog on the GREAT3 server, which is where we have the other HST-based catalogs.  If you are interested in that, you should coordinate with @joezuntz , who maintains that server.

- You can also mention the catalog on https://github.com/GalSim-developers/GalSim/wiki/RealGalaxy%20Data

- It would be appropriate in my opinion for you to put your writeup in devel/ or devel/external/AEGIS as a .tex file.  Perhaps you could do that on your branch that you've submitted for a pull request? 

- Would you be interested in some of the planned work on #795 and a more general version of #731? (which would be to potentially change from COSMOSCatalog() to HSTCatalog() or something like that, and enable it to take more generic filenames/directories, so you can use the COSMOSCatalog() functionality for AEGIS?)

**Comment by sowmyakth** [comment]
Hi @rmandelb, 
Thanks for the input. I am interested on working to making COSMOSCatalog() more general.  I'll go ahead and start with #795, and contact you if (more likely when) I have questions. 

The AEGIS catalog currently can be opened with COSMOSCatalog, but since I didn't do the parametric fit, there isn't any advantage in using it.

**Comment by joezuntz** [comment]
I can easily add it to the server if you give me a download link. If you get it to me this week I can put it ups straight away; if it's later than that there may be a slight delay as I leave Manchester at the end of the week and have to get visitor access set up to regain access to the server.

**Comment by rmandelb** [comment]
@sowmyakth - do you want to chat about how to do this on #795?  I was planning on doing the work myself and had already thought a bit about what to do, so I'm happy to discuss.

> The AEGIS catalog currently can be opened with COSMOSCatalog, but since I didn't do the 
> parametric fit, there isn't any advantage in using it.

If someone has code that already takes COSMOSCatalog, I think it's more convenient if they can swap between the COSMOS and AEGIS datasets by just using a different sample or filename, rather than changing the code so that it does COSMOSCatalog when using the COSMOS sample and RealGalaxyCatalog when using AEGIS.  This is particularly true given that the lines of code that make galaxies from the catalog look different for the two types of catalogs, so it's a bunch of code that would have to change.

**Comment by rmandelb** [comment]
@joezuntz - do you have someone who can be in the in-person babysitter of the server in your absence?  :)

**Comment by rmjarvis** [comment]
Merged via #806.
