### ISSUE TITLE
Incorrect value of magnification to conserve surface brightness after applying shear in Demo 6.

### ISSUE THREAD

**Issue by shobhit16** [GalSim-developers/GalSim#786]
I was going through demo6 recently, and it seems that the value of the magnification applied to conserve surface brightness after the application of shear is incorrect.

The specific lines I'm referring to are:

```
shear : 
        type : G1G2 
        g1 : -0.027
        g2 : 0.031

# Also apply a magnification mu = ( (1-kappa)^2 - |gamma|^2 )^-1
# This conserves surface brightness, so it scales both the area and flux.
magnify : 1.082

```

For the same value of shear, the 'mu' (or magnification) that I get from my calculation is 1.0017 instead of 1.082 as mentioned in the example. To confirm this, I ran a small test to compare the value I calculated against the value provided in the example in their ability to conserve the surface brightness, and it appears that my number performs better than the one given in the example. 

The details of the test are:
- Construct a Gaussian galaxy and calculate it's surface brightness (true surface brightness).
- Shear the above Gaussian galaxy.
- Apply the magnification I calculate to a copy of the sheared galaxy, and calculate it's surface brightness (calculated surface brightness).
- Apply the magnification given in the example to another copy of the sheared galaxy and calculate it's surface brightness (example surface brightness).

And the code is:
```
# Magnification Check

import galsim
import numpy as np

image_size = 64

images = []
for i in range(3):
	images.append(galsim.Image(image_size, image_size))

gal_flux = 1.e5    # total counts on the image
gal_sigma = 3.     # arcsec

pixel_scale = 0.2

sb_factor = (image_size ** 2) * pixel_scale

gal = galsim.Gaussian(flux=gal_flux, sigma=gal_sigma)

# Drawing Image
gal.drawImage(image = images[0], scale=pixel_scale)

# Calculate Surface Brightness of the Non-Sheared Galaxy
print "Actual Surface Brightness :::"
print np.sum(images[0].array)/sb_factor


gal_sh = gal.shear(g1 = -0.027, g2 = 0.031)

# Apply magnification to conserve surface brightness after applying shear

# Calculated
gal_cal = gal_sh.magnify(1.0017)
# Drawing Image
gal_cal.drawImage(image = images[1], scale=pixel_scale)

# Example
gal_ex = gal_sh.magnify(1.082)
# Drawing Image
gal_ex.drawImage(image = images[2], scale=pixel_scale)

# Calculate Surface Brightness of the Sheared Galaxy
print "Calc Mag Surface Brightness :::"
print np.sum(images[1].array)/sb_factor

print "Example Mag Surface Brightness :::"
print np.sum(images[2].array)/sb_factor
```

The numbers that I obtain are:

True Surface Brightness: 114.17
Calculated Surface Brightness: 114.24
Example Surface Brightness: 121.55

which says that my calculated number performs better than the one given in the example. 

Should a correction be made?

**Comment by rmjarvis** [comment]
> Should a correction be made?

No.  The code is correct.  I think you are misunderstanding what is meant by surface brightness.  It is not the total flux divided by the total area of the postage stamp.  Rather it is the local d(flux)/d(Area) at any given point in the galaxy profile.  This is kept constant by both the `shear` and `magnify` functions.

Here is some code that demonstrates that the local surface brightness at the center of the profile isn't changing as we shear and magnify the profile:
```
>>> import galsim
>>> gal = galsim.Gaussian(flux=1e5, sigma=3)
>>> gal.xValue(0,0)
1768.388256576615
>>> gal_sh = gal.shear(g1 = -0.027, g2 = 0.031)
>>> gal_sh.xValue(0,0)
1768.388256576615
>>> gal_mag = gal.magnify(1.082)
>>> gal_mag.xValue(0,0)
1768.388256576615
```
It's a bit complicated to figure out what locations in the sheared and magnified profiles correspond to other locations than (0,0), but every point in the original should have a 1-1 mapping with a point in these profiles with exactly the same surface brightness.

We can also look at what is happening with the flux:
```
>>> gal.flux
100000.0
>>> gal_sh.flux
99999.99999999997
>>> gal_mag.flux
108200.00000000001
```

And the size:
```
>>> gal.calculateHLR()
3.5322300675464238
>>> gal_sh.calculateHLR()
3.5347504916065149
>>> gal_mag.calculateHLR()
3.7039085659330562
```
So `shear` preserves flux and surface brightness, but modifies the size slightly (and of course the shape significantly).  And `magnify` preserves surface brightness, but not size or flux.  The flux in fact has increased by exactly the factor `mu`.

Also, I should mention that the comment that you pointed out was not meant to imply that the calculated value of mu was something special based on the given shear values.  Rather, this magnification was an arbitrary choice that would in this case be mostly due to an unspecified convergence (kappa).  We just give the full formula to remind lensing aficionados what we mean by mu.

Hopefully this is clearer now.
