### ISSUE TITLE
weighting galaxy postage stamps for RealGalaxy / COSMOSCatalog

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#787]
As described in http://adsabs.harvard.edu/abs/2012MNRAS.420.1518M , the COSMOS galaxy postage stamps were cut out in a way that creates a slight bias against large galaxies.   This trend is a weak one for most of the magnitude range that people use in practice (it's really severe only for the very bright, rare objects).  But still, it would be good to have an automated way to probabilistically reweight the sample to remove this bias.

I anticipated that we might want to do such reweighting, so the catalogs contain the weight factor you'd have to use to correct for this; it's stored as a float between 0-1 and for RealGalaxyCatalog you can access it as

```
rgc = galsim.RealGalaxyCatalog(...)
weight = rgc.weight
```

This issue is for two code changes:

1) The minor change is that I'd like to expose the weights for the COSMOSCatalog class to.  Right now you have to do

```
cc = galsim.COSMOSCatalog()
rgc = galsim.RealGalaxyCatalog(...)
weight = rgc.weight[cc.orig_index]
```

to account for the fact that cuts get applied on COSMOSCatalog but not on RealGalaxyCatalog.  This is admittedly only two extra lines of code, but still, there's no reason not to expose the weight in COSMOSCatalog directly and make it do that bookkeeping internally (and not load the catalog twice!).

2) If you want to use the weights, you'd have to do something like choose an index in the catalog, then use a random number generator like this:

```
ud = galsim.UniformDeviate()
if ud() < weight[ind]:
    # use this galaxy
else:
    # skip this iteration
```

I think it would be useful to have a helper function that returns a set of random indices into the catalog without / with the weights taken into account.  This could be a method of COSMOSCatalog and of RealGalaxy called `rand_indices` with a `weight=True` or `False` kwarg.  If `weight=False` then it would literally just permute the indices of the catalog and return however many of them the user requested.  If `weight=True` then it would also use the weights to remove the size bias.

I think (1) is uncontroversial, but thoughts on (2) are welcome.

I plan to do this after tagging v1.4.

**Comment by jmeyers314** [comment]
Should `blah = RealGalaxy(rgc, random=True)` also respect the weights?

**Comment by rmandelb** [comment]
Hmmm, it should probably have a kwarg to decide how to behave, but i'm not sure what the default should be.

**Comment by rmandelb** [comment]
@rmjarvis - I could use some feedback from you on a code design issue related to config functionality.

I added the ability to choose random galaxies weighted by the weight factors in the catalog.  That part was easy.  However, I also wanted to enable this via config, with the idea being that one might want to allow users to draw random galaxies using the weight factors.  That's something that I'm interested in doing myself (so this is not just speculation about what random users might want :)

For RealGalaxy this was easy and everything seems to work fine (by "everything", I mean there are unit tests demonstrating consistency between selecting a random object using python or config).

For COSMOSGalaxy this was trickier... I thought I had something that worked, but (a) a unit test has an error (I might just be doing something dumb here - did not dig into it enough) and (b) when I changed demo11.yaml to do this, something is clearly getting out of sync with the RNGs.  If I compare the demo11.py and demo11.yaml outputs, there are galaxies at the same locations (good), and they appear to be the same randomly-selected galaxies (also good), but the position angles for a given instance are not the same (bad).

I can dig into (a) myself, but first I wanted to check whether you have any thoughts on how I've attempted to make this work.  Are there any issues with the code design itself, or does it seem OK and I've just missed some small detail related to self-consistent RNG treatment within config that is causing problem (b)?

**Comment by rmjarvis** [comment]
Well, there is a problem in getting rid of the `SetDefaultIndex` bit.  You need this to make `'index': {'type': 'Random'}` work properly, since it needs to set the maximum value for the random integer.  I think you only want to skip that line if there is no `index` at all in the config parameters:
```
if 'index' in config:
    galsim.config.SetDefaultIndex(config, cosmos_cat.getNObjects())
```

As for the mismatch between the config and python versions, I predict that you will find them to be in sync when you run `galsim demo11.yaml image.nproc=1`.

The problem here is that when running with multiple processes, the rng gets serialized when communicating between the processes.  The input objects all live in the main process (so we don't have nproc copies of the cosmos catalog in memory).  When you call `selectRandomIndices`, the rng you give it as a kwarg gets serialized and then reconstituted on the other side.  This means the one in the child process building the galaxy doesn't actually change.

See `input_powerspectrum` for another case of this.  For that case, the number of random calls was deterministic, so I added a function `nRandCallsForBuildGrid` that returned the number of values to `discard` in the child process.  In your cases, `selectRandomIndices` may call the rng a variable number of times, so the same solution won't work.

You have two options I think.  
1. Have `selectRandomIndices` (optionally) also return the number of times the random number generator was called.  Then if you're using a proxy (cf. config/input_powerspectrum.py for how to check this) discard that many from the rng you have there.  

2. Make `selectRandomIndices` a `staticmethod` similar to `_makeSingleGalaxy`.  Then it will be run from the current process and the rng will be updated properly.  You can't use any attributes in that case, but you might be able to do everything you need via method calls, similar to what `_makeSingleGalaxy` does.

**Comment by rmandelb** [comment]
> I think you only want to skip that line if there is no index at all in the config parameters:

Oops.  Yes, that's right, thanks.

> As for the mismatch between the config and python versions, I predict that you will find 
> them to be in sync when you run galsim demo11.yaml image.nproc=1.

That's also right, so thanks for that.

Regarding the two options, I think either would be pretty easy, so I semi-randomly choose to implement the first one.

**Comment by rmandelb** [comment]
Closing #787.
