### ISSUE TITLE
small config bug

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#792]
There's a line in galsim/config/noise.py that does this:
```
cn -= galsim.UncorrelatedNoise(rng, im.wcs, current_var)
```

However, the call sequence for galsim.UncorrelatedNoise requires the arguments to be in the order variance, rng, scale, wcs.  So it's breaking with a TypeError as it tries to use the supplied rng as a noise variance.

The fix for this is obvious and I can do it on a branch (+look for other places where UncorrelatedNoise and CorrelatedNoise might be called incorrectly, but I think this might be it).  The harder question is can we design a unit test that would catch this kind of thing?  It's hard to come up with a really fast one, but I'm happy to get your ideas.

**Comment by rmjarvis** [comment]
A TODO item that I have not gotten around to yet is to make more unit tests of the config apparatus.  I've been lazily counting on check_yaml as my pseudo-test suite for this, but of course that only checks things that we have somewhere in a demo.

This particular bug happens when you have galaxies with noise, whiten them, and then add COSMOS-correlated noise to the full image.  So, not something that we have in a demo anywhere.

In any case, it's worth at least adding a test that catches this particular bug.  I did so on this branch: b137e522e1801a  It catches the bug you found and it is fixed by your commit.

**Comment by rmandelb** [comment]
Thanks Mike.  I'm making a PR in a moment.

**Comment by rmandelb** [comment]
Closing #792.
