### ISSUE TITLE
config verbosity for COSMOSCatalog

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#804]
I want to recommend that config by default (i.e., for the default verbosity level) say a little more about what it's doing with galaxies drawn from COSMOSCatalogs.

In particular, I have had multiple issues (like #802) where it would have been really helpful if the default verbosity level would issue a single statement at the start of a given file saying (a) exactly what catalog is being used and (b) whether the galaxies are real or parametric.

For example, in #802, I had used a template with parametric galaxies, then had the .yaml file later modify to use real galaxies, except it quietly ignored that.  It took me ages before I realized it was not in fact using real galaxies.  I had to go all the way up to verbosity=3, and then notice that it was calling the galaxy generator for parametric galaxies.  If the default verbosity had a single statement at the start of making each large image saying what COSMOSCatalog was used, and how it's being used, I think that would make debugging simple without adding too much clutter to the outputs.

Thoughts?

**Comment by rmjarvis** [comment]
The place to do this would be in `galsim/config/input_cosmos.py`.  Specifically, the (currently quite short) function `COSMOSLoader.setupImage`.  This is the function that gets run at the start of each large image when there is a cosmos_catalog item to process.  

The current function outputs how many objects are in the catalog total and how many passed the initial cuts, since I thought those were interesting bits of information people might want.  But you could certainly add additional lines there that you think would be useful.

The other option would be to override `getKwargs`.  Currently it is using the base class implementation (in `galsim/config/input.py`), but you could modify that to first run the base class version and then output some logging statement about the file name and options for the COSMOSCatalog that is about to be built.

**Comment by rmandelb** [comment]
OK, will try it out.  Thanks.

**Comment by rmandelb** [comment]
Closing #804.
