### ISSUE TITLE
drawImage creates an image with all zeros

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#834]
I'm working on master a6e94d1a782aeb6009f7c1d933106fe358612e75

I've found a situation where drawImage creates a zero image when an interpolated image is convolved with an analytic profile and a full wcs is used.  This does not occur if a simple scale is used.  I've attached a tar ball with code and images that reproduce the error.

[galsim-bug.tar.gz](https://github.com/GalSim-developers/GalSim/files/599783/galsim-bug.tar.gz)

**Comment by rmjarvis** [comment]
Thanks for the report Erin.  I can at least confirm that I get the same behavior.  Also, it was not broken in v1.4 (both paths give similar sums).  

So I'll `git bisect` to figure out what change broke it.  (Probably something I did on #799 if I had to guess.)

**Comment by rmjarvis** [comment]
Turns out the InterpolatedImage stuff was all a red herring.  Here is a stripped down example that also gives the same error:
```
    gal = galsim.Gaussian(sigma=2)
    psf = galsim.Gaussian(sigma=1)
    psf_inv = galsim.Deconvolve(psf)
    newpsf=galsim.Gaussian(sigma=1.1)
    final = galsim.Convolve(gal, psf_inv, newpsf)
    newim = final.drawImage(nx=25,ny=25,
                            wcs=galsim.JacobianWCS(0,0.5,0.5,0),
                            method='no_pixel')
```
I found the problem, which was in the Deconvolve class.  It was iterating over the image wrong when drawing in k-space with non-rectilinear k steps.  And yes, this was my error in doing some of the conversions in #799.

I'm adding a version of your script to the unit tests and should have a PR for the fix shortly.
