### ISSUE TITLE
installation FAQ could use some cleanup

### ISSUE THREAD

**Issue by rmandelb** [GalSim-developers/GalSim#897]
While I was browsing the installation FAQ I found some really out of date stuff (e.g., implying that we don't support NumPy 1.8 because it's not stable enough, which was true many years ago but now we're way past that version).  It could use some cleanup, maybe before we advertise the next tagged release?

**Comment by rmjarvis** [comment]
I started a [new FAQ page](https://github.com/GalSim-developers/GalSim/wiki/Installation-FAQ-(pip,-setup.py)) for the new version 2.0 installation procedure.  It's pretty spare right now, since I don't really know what the common questions will be.  But we'll populate that over time as we see what the issues are.

I'm not super inclined to go through the old [FAQ](https://github.com/GalSim-developers/GalSim/wiki/Installation-FAQ-(SCons)) and figure out which items are obsolete for SCons installations though.  So, ok to close this?
