### ISSUE TITLE
More WFIRST Updates

### ISSUE THREAD

**Issue by rmjarvis** [GalSim-developers/GalSim#919]
Some updates that Rachel didn't get to in branch #675.  I'm making a new issue for these to refocus the effort to this list of remaining tasks:

* Updating Zernikes since cycle 5
* Incorporating their variation across the SCAs
* Any other changes in cycle 7 besides the ones listed above as going into this PR!
* Make WFIRST module components accessible in config
* Dither sequences (re-think connection to Chris's code)
* Simpler persistence specifications
* Brighter-fatter: empirically-based Antilogus-type implementation (CDModel) using coefficients measured by Chris
* Correlated read noise: should store a correlation function in WFIRST module and use it to generate the read noise. [no new coding needed]
* Individual pixel effects: ability to put in a flat field including effects down to the sub-pixel level. Cross-hatching pattern could then be simulated.
* Defects like cosmic rays
* Re-enable WCS tests that were removed because we no longer have a sample WCS from the WFIRST project office.

People interested in doing a subset of these should feel free to spin off separate issues as appropriate.

**Comment by rmandelb** [comment]
I received an update to the cycle 7 WCS from the WFIRST project office, so now I can do a fully self-consistent update to the whole module and re-enable some of the unit tests.

**Comment by rmandelb** [comment]
@rmjarvis - no rush, but I could use some advice about the user interface for some of the updates I'm planning for the WFIRST PSFs.  (And by "I'm planning" I mean "I already got all the inputs set up, so the user interface is the bit that I'm stuck on".)

As you may recall, currently getPSF() returns a dict containing PSFs for each SCA.  These PSFs will be either ChromaticOpticalPSFs or, if an effective wavelength was specified, an OpticalPSF.  Use of `approximate_struts` means it'll use 6 radially-oriented equally-spaced struts rather than the full pupil plane image (ignoring the variation in pupil plane image for long- and short-wavelength bands).  We also only used the Zernike info for the center of each SCA.   Because of the assumptions here -- no variation within an SCA and no variation of pupil plane image with band -- we really only needed to return a dict of PSFs indexed by SCA.

But now I want to enable the following:
* Different pupil plane image for long- and short-wavelength bands (only relevant if `approximate_struts=False`).
* variation of Zernikes across an SCA

There is more complexity now: a new PSF must be built depending on the bands to be used and the position within an SCA.  I would also like to not break people's old code; there are many situations where just having a single PSF for a given SCA is perfectly fine (e.g. tests of things that don't have a lot to do with knowing the PSF perfectly).

The easiest thing I could imagine doing is update the current `high_accuracy` kwarg, which ratchets up some of the accuracy settings if set to True (and defaults to False), and change it so that if `high_accuracy` is set it takes additional kwargs for the pupil plane to use and the location within an SCA (default to center of SCA).  Then in that case, it just returns a single PSF object for the given SCA+location+wavelength range with high accuracy settings.  Basically, this assumes that people who care very much about avoiding aliasing due to the struts also probably want a more realistic PSF and its variation within the SCA (and visa versa).  And it assumes that those who are willing to take a bit less numerical accuracy also might not care about variation within the SCA, or differences in the pupil plane configuration for different bands.  I could imagine these assumptions often being correct, but maybe not always.  This has the advantage of preserving the old behavior in many situations, while having a single clear way for users to indicate that they care about high-fidelity representation of the PSF. 

Other ideas?  Or does this sound OK?

**Comment by rmjarvis** [comment]
I think the former already fits in well with the current paradigm of returning a dict.  Just the pupil plane image would be different for different bands.  If there is an efficiency consideration, this could be enabled only if `high_accuracy=True`, but I doubt there is, so I'd just have it always use the right pupil plane image for each band whenever `approx_struts=False`.

The variation across the focal plane would normally require the user to call this function repeatedly -- once for each location on the focal plane where the PSF is requested.  For this, I suspect we want to add a new kwarg, `image_pos`, which would normally be just a `PositionD`, and SCAs would just be a single number.  But in general, the user could provide a list for each of them.  (SCAs is currently either a list of a single integer.)  The default `image_pos` would be the center of the image (2044, 2044) if the user doesn't specify something else.

**Comment by rmandelb** [comment]
> I think the former already fits in well with the current paradigm of returning a dict. 

Not really, unless I am missing something.  Right now, we get a single ChromaticOpticalPSF for a given SCA (so the dict is indexed by SCA).  Then users can use it to draw into whatever band they choose -- and the decisions happens later on.  Once the pupil plane image depends on the wavelength, there would have to be a long- and short-wavelength ChromaticOpticalPSF for a given SCA, and you choose which one to use depending on which band you want to draw into.  This new feature would require specifying the band at the time of calling getPSF(), or the creation of two PSFs for each SCA which makes the output more complicated.

**Comment by rmjarvis** [comment]
You're right.  I was confused.  I was thinking of the SCAs being the bandpasses rather than the sensors.

So I guess we need a bandpass argument as well.  Indeed, maybe that would be a good choice anyway, since we currently have wavelength_limits to give the range over which the chromatic effects should be implemented.  If we provided a bandpass instead, then these limits would be already implicit from the bandpass, which would be (typically) simpler.

It's starting to seem that probably there is not much advantage to having the PSFs indexed by SCAs, since there are other things that vary too, which are probably equally relevant.  Is there any efficiency gain in calculating them all at once and returning the lot of them as a dict rather than letting the user do it themselves:
```
PSFs_by_SCA = { SCA : galsim.wfirst.getPSF(SCA, approximate_struts=True, bandpass='H158') 
                for SCA in range(1,19) }
```
If not, then maybe we should just have the `getPSF` function return a single PSF and the user could store them into a dict as desired.  E.g. maybe using just a canonical SCA is fine, but they need the different bandpasses, so storing in a dict by bandpass is more useful.

**Comment by rmandelb** [comment]
Well, `wavelength_limits` is only use if you want to interpolate the chromatic info.  If you want a ChromaticOpticalPSF without interpolation then it's not relevant.  So in the current paradigm I think not requiring a bandpass is fine (and indeed it allows flexibility to have PSF objects that are usable in >1 bandpass).

The model you are proposing gives more freedom for the user to decide how they want to let things vary (are they mainly looking at testing chromatic effects?  Position-dependent PSF effects?) but it isn't backwards compatible.  Do you think that's an issue?

In principle if I were designing this from scratch and not worrying about what things looked like before, I would allow inputs for bandpass, SCA, and position within the SCA.  The third of these could be none (in which case you default to center of SCA).  If some are lists/arrays and others are not, then the ones that are not are assumed to be the same for each object -- e.g., you could have a list of positions and just a single SCA number, and it would assume you meant those positions are all within that single SCA.  Then it would return a single object or a list of objects depending on whether you just asked for one object or multiple.  It could take advantage of whatever efficiencies there are for those inputs (e.g., if you ask for a full chromatic optical PSF with no interpolation, for two long-wavelength bands that have the same pupil plane, evaluated at the same position -- then that can actually be the same object).  Some of the other settings, like `n_waves` and `wavelength`, could also be lists/arrays.

**Comment by rmandelb** [comment]
@rmjarvis - I'm implementing the updated getPSF() functionality, and realized something:

They gave me aberrations at 5 positions within each SCA: the center, and the four corners.

This is a bit weird because it's not a regular grid, so there isn't an obvious way to e.g. use bilinear interpolation.  The only ideas I came up with myself are kind of kludgy, e.g., bilinear interpolation of the corner ones (ignoring the center), bilinear interpolation of the corner ones (but taking a weighted average of that result and the center one, where the weight depends on the distance to the center).  Am I missing some obvious option?

**Comment by rmjarvis** [comment]
Another option would be to first do linear interpolation along each edge to get 4 more points.  And then do bilinear in each quadrant.

So (0,0.5) is average of (0,0) and (0,1), etc.
Then (0.123, 0.834) is bilinear interpolated from (0,0.5), (0,1), (0.5,0.5), (0,5.1).

I don't know if this is optimal in any sense.  I guess one way to check how much this even matters is to see how different the given (0.5,0.5) value is from the bilinear interpolated value from the 4 corners.  It might be a moot point and just using the corners is sufficient.

**Comment by rmandelb** [comment]
Ah ha, good point.  I just wrote a script to quickly loop over all SCAs and aberrations, and for each one, calculate the following:

- the mean value of that aberration (mean over the four corners, that is -- so what you'd get from bilinear interpolation to the center position)
- the fractional error at the center, defined as (mean value - actual value at center) / (actual value)

Then I histogrammed the values of fractional errors, because I have ~20 Zernikes for each of 18 SCAs so I can look at the distribution of fractional errors.  The 16th and 84th percentile values are -0.01 and 0.05.  There are a few extreme outliers, but generally it's tightly peaked around 0.  So, I think I can simply ignore the center value and do bilinear interpolation between the corner values.

**Comment by rmandelb** [comment]
@rmjarvis - I was wondering if you might be able to look at my restructured getPSF() and give comments on whether you think I'm on track towards something reasonable?  In short, here's what I've done to implement my suggestion from https://github.com/GalSim-developers/GalSim/issues/919#issuecomment-354663583 -

- updated input kwargs and how they are parsed
- I broke all the PSF creation out of getPSF() itself.  Instead, there is an internal routine that creates a single PSF.  getPSF() calls it however many times it needs to.
- roughly updated the documentation of getPSF() to reflect the changes

I didn't fix unit tests, the WFIRST demo, storePSFImages, or anything else that will be broken by this change in what getPSF() returns.  It'll be some more work to do that, so I wanted to first get some feedback about whether this structure makes sense and whether it's OK to break people's code with the new way of returning PSFs?  (I don't see an easy way to make this backwards compatible given that we now have the pupil plane depend on the wavelength, so even if we wanted to enable a dict based on the SCAs that are input, it's no longer the case that a single ChromaticOpticalPSF can represent all bands)

If you'd prefer I make a bogus PR to make it easier to compare the code, I'm happy to do that...

**Comment by rmjarvis** [comment]
Some comments about the changes to getPSF:
* I never really liked the dict return value, so I'm fine with getting rid of that.  Even if this isn't backwards compatible.  (It's less important I think for submodules to strictly keep backwards compatibility.)
* I think would go another step and just have getPSF only ever return a single PSF.  So `SCA` needs to be a single number, and the return value would always be a single PSF object.  It looks like the only efficiency concern to this is that you currently do a fairly complicated bit to reuse PSFs that are identical except for the bandpass but have the same pupil plane type.  I think this is something we can just leave to the user and just tell them about `galsim.wfirst.longwave_bands` and `galsim.wfirst.shortwave_bands` (or provide a helper function front end to them if you prefer) and let them reuse the PSF objects by hand.  I think this will normally fit easily into their code and would get rid of some complicated bits in getPSF.
* I would add 'long' and 'short' as allowed values for the `bandpass` parameter to help point out the likely efficiency gain to be had from just building two PSF objects for each SCA if you are planning to draw all the bands.
* To aid in transition, we could have the default bandpass be something other than None (say 'undefined') and provide a useful error message if the user doesn't give the bandpass, telling them why they need to and what the new API is.  Add a comment that this bit can be removed when we get rid of 2.x deprecations.

**Comment by rmandelb** [comment]
@rmjarvis thanks for rebasing, and for the getPSF feedback!

**Comment by rmandelb** [comment]
I plan to finish this issue off over winter break.  Troxel has reported that the WCS can sometimes be substantially off from Chris's code, so I should investigate that on this branch.

**Comment by rmandelb** [comment]
@matroxel has offered to provide an example that illustrates the issue.

**Comment by rmandelb** [comment]
Closing #919 (will open a new issue for remaining tasks).
