### ISSUE TITLE
galsim installed under different directory

### ISSUE THREAD

**Issue by esheldon** [GalSim-developers/GalSim#979]
Using `python setup.py install` I am seeing that galsim is now being installed under directories like this
```bash
.../lib/python3.6/site-packages/GalSim-2.0.0-py3.6-linux-x86_64.egg/galsim/
```
As opposed to the usual behavior of
```bash
.../lib/python3.6/site-packages/galsim/
```
In the latter case, an egg file would be present also, but not a directory with the egg name.

This is non-standard, which is itself a problem I think because it can cause confusion (I was confused!). But more importantly, if an existing install is already in place under the plain `galsim` directory, as shown in the second version, it will be used before the newer install shown in the first version.  In fact I discovered this problem because I was not seeing my updates when I ran `python setup.py install`

**Comment by rmjarvis** [comment]
So, I think this is actually the standard behavior for `python setup.py install`.  It normally installs eggs rather than wheels.  `pip install .` will do the more modern thing and install a wheel along with the flat `galsim` directory.

What seems to be non-standard is that we have `zip_safe=False` as a parameter to `setup()`, which is supposed to tell it to install the unzipped directory (`galsim`) along with an `.egg-info` file rather than installing the `.egg` zipped directory.  And for some reason, it is not respecting that.  I Googled around for a bit and couldn't find any solution.  Some other people with the same problem, but generally workarounds rather than actual solutions.

The workaround that I can suggest for now is to do
```
pip install .
```
rather than
```
python setup.py install
```
That will install a flat directory and a `.dist-info` file.

I think the longer term solution that I'll keep looking for is to figure out how to make `python setup.py install` install a wheel like pip does, rather than the egg.  But I don't know how to do that yet.

**Comment by esheldon** [comment]
Just to give my perspective, the standard is to install an egg file *and* the directory with the package name.  And to be clear, that is an egg *file* not a directory with .egg extension on it.

This has been the standard since as early as 2004 when I started making packages.  If you write the simplest setup.py and use distutils that is what happens.  Maybe with setuputils it has some different behavior?  I generally avoid setuputils because it does things in a nonstandard way and breaks my work flow, so I can't really comment.

I can't use `pip install .` when developing because it won't do a reinstall when I make changes.

**Comment by rmjarvis** [comment]
> I can't use pip install . when developing because it won't do a reinstall when I make changes.

It seems to reinstall things for me.  (Both changes to .py files are installed and changes to C++ files cause a rebuild of the .so file.)

However, it's also really slow, since it makes sure to resolve all dependencies first.  So probably the better solution for development is to just `pip uninstall galsim` to get rid of old versions and use the normal `python setup.py install`.  The fact that it installs into a .egg file shouldn't be an issue then.

**Comment by rmjarvis** [comment]
I added a FAQ entry about this:
https://github.com/GalSim-developers/GalSim/wiki/Installation-FAQ-(pip,-setup.py)#python-setuppy-install-doesnt-supersede-older-galsim-installation

**Comment by rmjarvis** [comment]
I assume this is ok to close now.  Please reopen if there is any further action requested.
