### ISSUE TITLE
Floating Point Bug

### ISSUE THREAD

**Issue by dannygoldstein** [GalSim-developers/GalSim#983]
If one creates a DeltaFunction with a flux below the smallest single precision number, then modifies it using withFlux to be above single precision, drawImage fails with all nans:

```
ipdb> df = galsim.DeltaFunction(1e-60)
ipdb> df2 = df.withFlux(1e-10)
ipdb> psf = galsim.Gaussian(0.2).withFlux(1.)
ipdb> conv = galsim.Convolve([df2 ,psf])
ipdb> conv.drawImage(scale=0.2)
galsim.Image(bounds=galsim.BoundsI(xmin=1, xmax=12, ymin=1, ymax=12), array=
array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],
      dtype=float32), wcs=galsim.PixelScale(0.2))
ipdb> conv = galsim.Convolve([df ,psf])
ipdb> conv.drawImage(scale=0.2)
galsim.Image(bounds=galsim.BoundsI(xmin=1, xmax=12, ymin=1, ymax=12), array=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32), wcs=galsim.PixelScale(0.2))
```

**Comment by rmjarvis** [comment]
I agree this is rather unfortunate behavior.  

But I'll point out that this only happens when drawing onto a single-precision Image.  If you do `conv.drawImage(scale=0.2, dtype=float)`, it can handle it fine.  The problem is that you are having it draw first with 1.e-60, then scaling it up by a factor of 1.e50.  These operations are problematic at single precision.

So is this an important use case that you think needs fixing?  Or just something that is an interesting by-product of the implementation details of how GalSIm draws images?

**Comment by dannygoldstein** [comment]
Didn't know you could pass dtype=float. That solution works fine for me.

Thanks.

Danny

**Comment by rmjarvis** [comment]
You can even convert back to single-precision at the end before writing the image to disk or something if you want: `im32 = galsim.Image(im64, dtype=numpy.float32)`.  Or even `int32` or `int16` or unsigned versions of these are allowed.

Also, if clearer, using `dtype=numpy.float64` in the `drawImage` call is equivalent to `dtype=float`, since python floats are 64 bit.  We made 32 bit the default dtype because that's the more common image data type in astronomy, and double precision is usually unnecessary and would just increase the disk load of making a bunch of images.
